/**
 * WaterNeuron protocol data for ICP reward estimation.
 *
 * Gold DAO holds WTN staked in 4 SNS neurons. WaterNeuron distributes 10% of
 * the ICP maturity generated by its two NNS neurons to all WTN SNS stakers,
 * proportional to stake. This module fetches the two inputs needed to
 * calculate Gold DAO's share of that 10%:
 *
 *   1. The NNS neurons controlled by WaterNeuron (staked ICP, state, APY proxy)
 *      → via Candid `get_neuron_info` on NNS governance.
 *
 *   2. Total WTN staked in WaterNeuron governance
 *      → via Candid `get_nervous_system_parameters` + SNS API fallback.
 *
 * Called once on load (values change slowly). The consumer combines this with
 * the Gold DAO WTN total (already fetched in use-live-data.ts) to compute:
 *
 *   icp_from_wtn = maturity_annual × 0.10 × (gold_dao_wtn / total_wtn_staked)
 */

import { Actor, HttpAgent } from "@dfinity/agent";
import type { IDL as IDLType } from "@dfinity/candid";

const NNS_GOVERNANCE = "rrkah-fqaaa-aaaaa-aaaaq-cai";

/** WaterNeuron's two NNS neuron IDs */
const WTN_NNS_NEURONS = {
  /** 8-year neuron — always active, max dissolve delay bonus */
  EIGHT_YEAR: 433047053926084807n,
  /** 6-month neuron — funded by liquid stakers, periodically dissolves */
  SIX_MONTH: 13680855657433416220n,
} as const;

/** 10% of ICP maturity goes to WTN SNS stakers (protocol constant) */
export const WTN_FEE_PCT = 0.10;

/* ── NNS governance IDL (get_neuron_info only) ─────────────────────────── */

const nnsGovernanceIdlFactory = (({ IDL }: { IDL: typeof IDLType }) => {
  const KnownNeuronData = IDL.Record({
    name: IDL.Text,
    description: IDL.Opt(IDL.Text),
  });
  const NeuronInfo = IDL.Record({
    dissolve_delay_seconds: IDL.Nat64,
    recent_ballots: IDL.Vec(
      IDL.Record({
        vote: IDL.Int32,
        proposal_id: IDL.Opt(IDL.Record({ id: IDL.Nat64 })),
      }),
    ),
    neuron_type: IDL.Opt(IDL.Int32),
    created_timestamp_seconds: IDL.Nat64,
    state: IDL.Int32,
    stake_e8s: IDL.Nat64,
    joined_community_fund_timestamp_seconds: IDL.Opt(IDL.Nat64),
    retrieved_at_timestamp_seconds: IDL.Nat64,
    visibility: IDL.Opt(IDL.Int32),
    known_neuron_data: IDL.Opt(KnownNeuronData),
    voting_power: IDL.Nat64,
    age_seconds: IDL.Nat64,
  });
  const GovernanceError = IDL.Record({
    error_type: IDL.Int32,
    error_message: IDL.Text,
  });
  const Result = IDL.Variant({ Ok: NeuronInfo, Err: GovernanceError });
  return IDL.Service({
    get_neuron_info: IDL.Func([IDL.Nat64], [Result], ["query"]),
  });
}) as unknown as Parameters<typeof Actor.createActor>[0];

/* ── Types ──────────────────────────────────────────────────────────────── */

export interface NnsNeuronInfo {
  /** Staked ICP (whole units, not e8s) */
  stakedIcp: number;
  /** Current voting power */
  votingPower: number;
  /** Dissolve delay in seconds */
  dissolveDelaySec: number;
  /** Neuron age in seconds (0 when dissolving) */
  ageSec: number;
  /** 1 = not dissolving, 2 = dissolving, 3 = dissolved */
  state: number;
  /** true when state == 2 (dissolving) */
  dissolving: boolean;
}

export interface WaterNeuronData {
  /** 8-year NNS neuron info */
  neuron8y: NnsNeuronInfo | null;
  /** 6-month NNS neuron info */
  neuron6m: NnsNeuronInfo | null;
  /** Total WTN staked in WaterNeuron governance (whole WTN, not e8s) */
  totalWtnStaked: number | null;
  /**
   * Estimated annual ICP maturity across both neurons.
   * Uses the staked ICP × estimated effective APY for each neuron.
   * Null when neuron data is unavailable.
   */
  estimatedAnnualMaturity: number | null;
}

/* ── Agent singleton ────────────────────────────────────────────────────── */

let agentPromise: Promise<HttpAgent> | null = null;
function getAgent(): Promise<HttpAgent> {
  if (!agentPromise) {
    agentPromise = HttpAgent.create({ host: "https://icp-api.io" });
  }
  return agentPromise!;
}

/* ── Fetch a single NNS neuron ─────────────────────────────────────────── */

async function fetchNnsNeuron(
  neuronId: bigint,
): Promise<NnsNeuronInfo | null> {
  try {
    const agent = await getAgent();
    const actor = Actor.createActor(nnsGovernanceIdlFactory, {
      agent,
      canisterId: NNS_GOVERNANCE,
    });
    const result = (await actor.get_neuron_info(neuronId)) as
      | { Ok: Record<string, bigint | number> }
      | { Err: unknown };
    if ("Err" in result) return null;
    const info = result.Ok;
    const state = Number(info.state);
    return {
      stakedIcp: Number(info.stake_e8s) / 1e8,
      votingPower: Number(info.voting_power) / 1e8,
      dissolveDelaySec: Number(info.dissolve_delay_seconds),
      ageSec: Number(info.age_seconds),
      state,
      dissolving: state === 2,
    };
  } catch {
    return null;
  }
}

/* ── Estimate effective APY for a neuron ────────────────────────────────── */

/**
 * Rough effective APY for a neuron based on its dissolve delay and age.
 *
 * The NNS reward depends on: staked ICP × dissolve-delay bonus × age bonus.
 * Max dissolve delay (8y) gives +200% bonus → 3× multiplier.
 * Max age (4y on NNS) gives +25% bonus → 1.25× multiplier.
 * 8-year gang bonus: +10% for neurons at max dissolve delay.
 * A neuron with max everything: 3.0 × 1.25 × 1.10 = 4.125× voting power/ICP.
 *
 * BASE_NNS_APY is calibrated so that a neuron with 8y DD and ~1.5y age
 * produces ~8% effective APY (matching dashboard observations Sep 2026).
 * Actual rewards depend on total network voting power, proposal volume,
 * and participation — this is always an approximation.
 */
const BASE_NNS_APY = 0.09;
const MAX_DISSOLVE_DELAY_SEC = 8 * 365.25 * 24 * 3600; // 8 years
const MAX_AGE_SEC = 4 * 365.25 * 24 * 3600; // 4 years
const MAX_DD_BONUS = 2.0; // +200%
const MAX_AGE_BONUS = 0.25; // +25%
const GANG_8Y_BONUS = 0.10; // +10% for neurons at exactly max DD

function estimateEffectiveApy(neuron: NnsNeuronInfo): number {
  // Dissolve delay bonus: linear 0% → 200% from 0 → 8 years
  const ddFraction = Math.min(
    neuron.dissolveDelaySec / MAX_DISSOLVE_DELAY_SEC,
    1,
  );
  const ddBonus = 1 + MAX_DD_BONUS * ddFraction; // 1.0 → 3.0

  // Age bonus: linear 0% → 25% from 0 → 4 years (0 when dissolving)
  const ageFraction = Math.min(neuron.ageSec / MAX_AGE_SEC, 1);
  const ageBonus = 1 + MAX_AGE_BONUS * ageFraction; // 1.0 → 1.25

  // 8-year gang bonus: only for neurons at max dissolve delay
  const gangBonus = ddFraction >= 0.99 ? 1 + GANG_8Y_BONUS : 1.0;

  // Max multiplier: 3.0 × 1.25 × 1.10 = 4.125
  const maxMultiplier = (1 + MAX_DD_BONUS) * (1 + MAX_AGE_BONUS) * (1 + GANG_8Y_BONUS);
  const thisMultiplier = ddBonus * ageBonus * gangBonus;

  // Scale the base APY by this neuron's relative multiplier
  return BASE_NNS_APY * (thisMultiplier / maxMultiplier);
}

/* ── Fetch total WTN staked via SNS API ────────────────────────────────── */

/**
 * Try the SNS API v1 to get WaterNeuron SNS neuron statistics.
 * Falls back to null if unavailable.
 */
const WTN_SNS_ROOT = "jmod6-4iaaa-aaaaq-aadkq-cai";

async function fetchTotalWtnStaked(): Promise<number | null> {
  // Attempt 1: SNS API neuron stats
  try {
    const res = await fetch(
      `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}/neurons/stats`,
    );
    if (res.ok) {
      const data = await res.json();
      // Expected: { total_staked_e8s: number } or similar
      if (data.total_staked_e8s) {
        return Number(data.total_staked_e8s) / 1e8;
      }
      if (data.total_stake_e8s) {
        return Number(data.total_stake_e8s) / 1e8;
      }
    }
  } catch {
    /* try next */
  }

  // Attempt 2: SNS API root info (may include staked in metadata)
  try {
    const res = await fetch(
      `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}`,
    );
    if (res.ok) {
      const data = await res.json();
      if (data.total_staked_e8s) {
        return Number(data.total_staked_e8s) / 1e8;
      }
    }
  } catch {
    /* fallback below */
  }

  return null;
}

/* ── Public API ─────────────────────────────────────────────────────────── */

/**
 * Defaults when live data is unavailable.
 * Based on dashboard data from 2026-09-16.
 */
export const DEFAULTS = {
  /** Conservative estimate for total WTN staked in governance. */
  totalWtnStaked: 100_000_000,
  /** 8-year neuron staked ICP (from dashboard) */
  neuron8yStaked: 1_061_875,
  /** 6-month neuron staked ICP (from dashboard) */
  neuron6mStaked: 1_342_869,
} as const;

/**
 * Fetch all WaterNeuron protocol data needed for ICP-from-WTN calculation.
 * Called once on load. Returns null fields on partial failure — callers use
 * DEFAULTS for any null field.
 */
export async function fetchWaterNeuronData(): Promise<WaterNeuronData> {
  const [neuron8y, neuron6m, totalWtnStaked] = await Promise.all([
    fetchNnsNeuron(WTN_NNS_NEURONS.EIGHT_YEAR),
    fetchNnsNeuron(WTN_NNS_NEURONS.SIX_MONTH),
    fetchTotalWtnStaked(),
  ]);

  // Estimate annual maturity from whatever neuron data we got
  let estimatedAnnualMaturity: number | null = null;
  if (neuron8y || neuron6m) {
    let total = 0;
    if (neuron8y) {
      const apy = estimateEffectiveApy(neuron8y);
      total += neuron8y.stakedIcp * apy;
    }
    if (neuron6m && !neuron6m.dissolving) {
      const apy = estimateEffectiveApy(neuron6m);
      total += neuron6m.stakedIcp * apy;
    }
    // When the 6m neuron is dissolving, it earns minimal maturity — skip it
    estimatedAnnualMaturity = total;
  }

  return { neuron8y, neuron6m, totalWtnStaked, estimatedAnnualMaturity };
}

/**
 * Calculate the ICP/year that Gold DAO receives from WTN staking rewards.
 *
 * @param annualMaturity  Total ICP maturity/year from WaterNeuron NNS neurons
 * @param goldDaoWtn      Gold DAO's WTN staked (from use-live-data.ts wtnTotal)
 * @param totalWtnStaked  Total WTN staked in WaterNeuron governance
 */
export function calcIcpFromWtn(
  annualMaturity: number,
  goldDaoWtn: number,
  totalWtnStaked: number,
): number {
  if (totalWtnStaked <= 0 || goldDaoWtn <= 0 || annualMaturity <= 0) return 0;
  return annualMaturity * WTN_FEE_PCT * (goldDaoWtn / totalWtnStaked);
}
