/**
 * WaterNeuron protocol data for ICP reward estimation.
 *
 * Gold DAO holds WTN staked in 4 SNS neurons. WaterNeuron distributes 10% of
 * the ICP maturity generated by its NNS 8-year neuron to all WTN SNS stakers.
 * The share each neuron receives correlates with its voting power (VP)
 * relative to the total participating VP in the WTN governance.
 *
 * This module fetches:
 *   1. WaterNeuron's 8-year NNS neuron (staked ICP → estimated annual maturity)
 *   2. Gold DAO's WTN neuron VP (from the same 4 neurons already fetched)
 *   3. Total WTN governance VP (from a recent WTN SNS proposal)
 *
 * Formula:
 *   icp_from_wtn = maturity_annual × 10% × (gold_dao_vp / total_vp)
 */

import { Actor, HttpAgent } from "@dfinity/agent";
import type { IDL as IDLType } from "@dfinity/candid";

const NNS_GOVERNANCE = "rrkah-fqaaa-aaaaa-aaaaq-cai";
const WTN_SNS_ROOT = "jmod6-4iaaa-aaaaq-aadkq-cai";

/** WaterNeuron's NNS neuron IDs */
const WTN_8Y_NEURON = 433047053926084807n;
const WTN_6M_NEURON = 13680855657433416220n;

/** 10% of ICP maturity goes to WTN SNS stakers (protocol constant) */
export const WTN_FEE_PCT = 0.10;

/** Gold DAO's 4 WTN neuron endpoints (same URLs from api.ts) */
const GOLD_DAO_WTN_NEURON_URLS = [
  `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}/neurons/884ce73eb8022314f5a454feba94656a7bf3b80c2173c898dae0d7fcdd25b356`,
  `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}/neurons/238d59f677414f0f82c09b4c4b6975c3768818a0400f1c6ae5bad618be51bc22`,
  `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}/neurons/e6b2425b794513f375f8b44b94b6a41152db76b0b0c1122a863ee14a02f38a77`,
  `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}/neurons/cdeea7c0fcb8ded7c04ad21fbfdcd64347abfd6593e40d7e8e18f0e2b984f7ba`,
];

/* ── NNS governance IDL (get_neuron_info only) ─────────────────────────── */

const nnsGovernanceIdlFactory = (({ IDL }: { IDL: typeof IDLType }) => {
  const KnownNeuronData = IDL.Record({
    name: IDL.Text,
    description: IDL.Opt(IDL.Text),
  });
  const NeuronInfo = IDL.Record({
    dissolve_delay_seconds: IDL.Nat64,
    recent_ballots: IDL.Vec(
      IDL.Record({
        vote: IDL.Int32,
        proposal_id: IDL.Opt(IDL.Record({ id: IDL.Nat64 })),
      }),
    ),
    neuron_type: IDL.Opt(IDL.Int32),
    created_timestamp_seconds: IDL.Nat64,
    state: IDL.Int32,
    stake_e8s: IDL.Nat64,
    joined_community_fund_timestamp_seconds: IDL.Opt(IDL.Nat64),
    retrieved_at_timestamp_seconds: IDL.Nat64,
    visibility: IDL.Opt(IDL.Int32),
    known_neuron_data: IDL.Opt(KnownNeuronData),
    voting_power: IDL.Nat64,
    age_seconds: IDL.Nat64,
  });
  const GovernanceError = IDL.Record({
    error_type: IDL.Int32,
    error_message: IDL.Text,
  });
  const Result = IDL.Variant({ Ok: NeuronInfo, Err: GovernanceError });
  return IDL.Service({
    get_neuron_info: IDL.Func([IDL.Nat64], [Result], ["query"]),
  });
}) as unknown as Parameters<typeof Actor.createActor>[0];

/* ── Types ──────────────────────────────────────────────────────────────── */

export interface NnsNeuronInfo {
  stakedIcp: number;
  votingPower: number;
  dissolveDelaySec: number;
  ageSec: number;
  state: number;
  dissolving: boolean;
}

export interface WaterNeuronData {
  /** 8-year NNS neuron info (for maturity estimation) */
  neuron8y: NnsNeuronInfo | null;
  /** 6-month NNS neuron info */
  neuron6m: NnsNeuronInfo | null;
  /** Estimated annual ICP maturity from BOTH neurons (6m only when active) */
  estimatedAnnualMaturity: number | null;
  /** Sum of VP across Gold DAO's 4 WTN neurons */
  goldDaoWtnVp: number | null;
  /** Total VP in the WTN SNS (from most recent executed proposal) */
  totalWtnVp: number | null;
  /** Calculated: Gold DAO's share of WTN governance (0..1) */
  vpShare: number | null;
  /** Calculated: ICP/year Gold DAO receives from WTN rewards */
  icpFromWtnAnnual: number | null;
}

/* ── Agent singleton ────────────────────────────────────────────────────── */

let agentPromise: Promise<HttpAgent> | null = null;
function getAgent(): Promise<HttpAgent> {
  if (!agentPromise) {
    agentPromise = HttpAgent.create({ host: "https://icp-api.io" });
  }
  return agentPromise!;
}

/* ── 1. Fetch the 8-year NNS neuron ────────────────────────────────────── */

async function fetchNnsNeuron(
  neuronId: bigint,
): Promise<NnsNeuronInfo | null> {
  try {
    const agent = await getAgent();
    const actor = Actor.createActor(nnsGovernanceIdlFactory, {
      agent,
      canisterId: NNS_GOVERNANCE,
    });
    const result = (await actor.get_neuron_info(neuronId)) as
      | { Ok: Record<string, bigint | number> }
      | { Err: unknown };
    if ("Err" in result) return null;
    const info = result.Ok;
    const state = Number(info.state);
    return {
      stakedIcp: Number(info.stake_e8s) / 1e8,
      votingPower: Number(info.voting_power) / 1e8,
      dissolveDelaySec: Number(info.dissolve_delay_seconds),
      ageSec: Number(info.age_seconds),
      state,
      dissolving: state === 2,
    };
  } catch {
    return null;
  }
}

/* ── APY estimation for the 8-year neuron ──────────────────────────────── */

/**
 * Calibrated against dashboard (Sep 2026): 8y neuron → ~7.98% effective APY.
 * BASE_NNS_APY is the theoretical max-bonus APY; actual neurons get a fraction
 * proportional to their dissolve-delay, age, and 8y-gang bonus multipliers.
 */
const BASE_NNS_APY = 0.09;
const MAX_DISSOLVE_DELAY_SEC = 8 * 365.25 * 24 * 3600;
const MAX_AGE_SEC = 4 * 365.25 * 24 * 3600;
const MAX_DD_BONUS = 2.0;
const MAX_AGE_BONUS = 0.25;
const GANG_8Y_BONUS = 0.10;

function estimateEffectiveApy(neuron: NnsNeuronInfo): number {
  const ddFrac = Math.min(neuron.dissolveDelaySec / MAX_DISSOLVE_DELAY_SEC, 1);
  const ddBonus = 1 + MAX_DD_BONUS * ddFrac;
  const ageFrac = Math.min(neuron.ageSec / MAX_AGE_SEC, 1);
  const ageBonus = 1 + MAX_AGE_BONUS * ageFrac;
  const gangBonus = ddFrac >= 0.99 ? 1 + GANG_8Y_BONUS : 1.0;
  const maxMult =
    (1 + MAX_DD_BONUS) * (1 + MAX_AGE_BONUS) * (1 + GANG_8Y_BONUS);
  return BASE_NNS_APY * ((ddBonus * ageBonus * gangBonus) / maxMult);
}

/* ── 2. Fetch Gold DAO's WTN neuron VP ─────────────────────────────────── */

interface SnsNeuronResponse {
  stake_e8s: number;
  total_maturity_e8s_equivalent: number;
  voting_power?: number;
  dissolve_delay_seconds?: number;
  age_seconds?: number;
}

async function fetchGoldDaoWtnVp(): Promise<number | null> {
  try {
    const results = await Promise.all(
      GOLD_DAO_WTN_NEURON_URLS.map(async (url) => {
        const res = await fetch(url);
        if (!res.ok) return 0;
        const data: SnsNeuronResponse = await res.json();
        // The SNS API may return voting_power directly
        if (data.voting_power) {
          return Number(data.voting_power) / 1e8;
        }
        // Fallback: estimate VP from stake + dissolve delay + age
        // VP = stake × (1 + dd_bonus) × (1 + age_bonus)
        // WTN config: max DD 3y → +100%, max age 3y → +100%
        const stake = (data.stake_e8s + data.total_maturity_e8s_equivalent) / 1e8;
        const ddSec = data.dissolve_delay_seconds ?? 0;
        const ageSec = data.age_seconds ?? 0;
        const WTN_MAX_DD = 3 * 365.25 * 24 * 3600;
        const WTN_MAX_AGE = 3 * 365.25 * 24 * 3600;
        const ddBonus = 1 + Math.min(ddSec / WTN_MAX_DD, 1); // 1.0 → 2.0
        const ageBonus = 1 + Math.min(ageSec / WTN_MAX_AGE, 1); // 1.0 → 2.0
        return stake * ddBonus * ageBonus;
      }),
    );
    const total = results.reduce((a, b) => a + b, 0);
    return total > 0 ? total : null;
  } catch {
    return null;
  }
}

/* ── 3. Fetch total WTN VP from a recent proposal ──────────────────────── */

interface WtnProposal {
  id: string;
  decided_timestamp_seconds: number;
  tally?: {
    yes: number;
    no: number;
    total: number;
  };
  latest_tally?: {
    yes: number;
    no: number;
    total: number;
  };
}

async function fetchTotalWtnVp(): Promise<number | null> {
  try {
    // Get the most recent decided proposals from WTN SNS
    const res = await fetch(
      `https://sns-api.internetcomputer.org/api/v1/snses/${WTN_SNS_ROOT}/proposals?offset=0&limit=5&sort_by=-id`,
    );
    if (!res.ok) return null;
    const body = await res.json();
    const proposals: WtnProposal[] = Array.isArray(body)
      ? body
      : (body.data ?? []);

    // Find a decided proposal with tally data
    for (const p of proposals) {
      const tally = p.tally ?? p.latest_tally;
      if (tally && tally.total > 0) {
        return Number(tally.total) / 1e8;
      }
    }
  } catch {
    /* fallback */
  }
  return null;
}

/* ── Defaults ──────────────────────────────────────────────────────────── */

export const DEFAULTS = {
  /** From dashboard Sep 2026 */
  neuron8yStakedIcp: 1_061_875,
  /** 8y neuron effective APY from dashboard */
  neuron8yApy: 0.0798,
  /** Total VP in WTN governance from last proposal screenshot */
  totalWtnVp: 209_130_000,
  /** Gold DAO's WTN VP (estimated: 6.2M WTN × ~2.5 avg multiplier) */
  goldDaoWtnVp: 15_500_000,
} as const;

/* ── Public API ─────────────────────────────────────────────────────────── */

/**
 * Fetch all WaterNeuron data needed for ICP-from-WTN calculation.
 * Called once on load. Partial failures use DEFAULTS.
 */
export async function fetchWaterNeuronData(): Promise<WaterNeuronData> {
  const [neuron8y, neuron6m, goldDaoWtnVp, totalWtnVp] = await Promise.all([
    fetchNnsNeuron(WTN_8Y_NEURON),
    fetchNnsNeuron(WTN_6M_NEURON),
    fetchGoldDaoWtnVp(),
    fetchTotalWtnVp(),
  ]);

  // Estimate annual maturity from both neurons
  let estimatedAnnualMaturity: number | null = null;
  if (neuron8y || neuron6m) {
    let total = 0;
    if (neuron8y) {
      total += neuron8y.stakedIcp * estimateEffectiveApy(neuron8y);
    } else {
      total += DEFAULTS.neuron8yStakedIcp * DEFAULTS.neuron8yApy;
    }
    // 6m neuron only contributes when NOT dissolving
    if (neuron6m && !neuron6m.dissolving) {
      total += neuron6m.stakedIcp * estimateEffectiveApy(neuron6m);
    }
    estimatedAnnualMaturity = total;
  } else {
    // Full fallback: 8y only (conservative)
    estimatedAnnualMaturity =
      DEFAULTS.neuron8yStakedIcp * DEFAULTS.neuron8yApy;
  }

  // Use live VP or defaults
  const gdVp = goldDaoWtnVp ?? DEFAULTS.goldDaoWtnVp;
  const totVp = totalWtnVp ?? DEFAULTS.totalWtnVp;

  // Calculate share and ICP
  const vpShare = totVp > 0 ? gdVp / totVp : 0;
  const icpFromWtnAnnual =
    estimatedAnnualMaturity * WTN_FEE_PCT * vpShare;

  return {
    neuron8y,
    neuron6m,
    estimatedAnnualMaturity,
    goldDaoWtnVp: gdVp,
    totalWtnVp: totVp,
    vpShare,
    icpFromWtnAnnual,
  };
}

/**
 * Pure calculation — use when overriding values from assumptions UI.
 */
export function calcIcpFromWtn(
  annualMaturity: number,
  goldDaoVp: number,
  totalVp: number,
): number {
  if (totalVp <= 0 || goldDaoVp <= 0 || annualMaturity <= 0) return 0;
  return annualMaturity * WTN_FEE_PCT * (goldDaoVp / totalVp);
}
