/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, UserRole)),
  'err' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const WeekSummary = IDL.Record({
  'pot' : IDL.Nat,
  'treasurePerChip' : IDL.Nat,
  'treasuryKeep' : IDL.Nat,
  'chips' : IDL.Nat,
  'week' : IDL.Nat,
  'drawTicket' : IDL.Nat,
  'drawTickets' : IDL.Nat,
  'closedAt' : IDL.Int,
  'players' : IDL.Nat,
  'drawPrize' : IDL.Nat,
  'drawWinner' : IDL.Opt(IDL.Principal),
  'drawRandom' : IDL.Nat,
});
export const Result_5 = IDL.Variant({ 'ok' : WeekSummary, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const WeekStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'closing' : IDL.Null,
});
export const PayoutConcept = IDL.Variant({
  'draw' : IDL.Null,
  'prize' : IDL.Null,
});
export const Payout = IDL.Record({
  'to' : IDL.Principal,
  'concept' : PayoutConcept,
  'tiers' : IDL.Vec(IDL.Nat),
  'amount' : IDL.Nat,
});
export const AdminView = IDL.Record({
  'status' : WeekStatus,
  'drawCarry' : IDL.Nat,
  'week' : IDL.Nat,
  'lastClose' : IDL.Opt(WeekSummary),
  'burned' : IDL.Nat,
  'payouts' : IDL.Vec(Payout),
  'treasury' : IDL.Nat,
});
export const Result_3 = IDL.Variant({ 'ok' : AdminView, 'err' : IDL.Text });
export const GameConfig = IDL.Record({
  'status' : WeekStatus,
  'mines' : IDL.Nat,
  'feeE8s' : IDL.Nat,
  'minChips' : IDL.Nat,
  'cells' : IDL.Nat,
  'pointsTable' : IDL.Vec(IDL.Nat),
  'week' : IDL.Nat,
  'minPlayers' : IDL.Nat,
  'treasuryBps' : IDL.Nat,
  'chipPriceE8s' : IDL.Nat,
  'tierCutsPct' : IDL.Vec(IDL.Nat),
  'safePicks' : IDL.Nat,
  'tierMultBps' : IDL.Vec(IDL.Nat),
  'faucetCapE8s' : IDL.Nat,
  'excavationsPerChip' : IDL.Nat,
  'drawBps' : IDL.Nat,
  'diamondBps' : IDL.Nat,
});
export const TierIndex = IDL.Nat;
export const ChipView = IDL.Record({
  'id' : IDL.Nat,
  'diamonds' : IDL.Nat,
  'tier' : TierIndex,
  'used' : IDL.Nat,
  'avgX100' : IDL.Nat,
  'projectedX100' : IDL.Nat,
  'gapToNextX100' : IDL.Opt(IDL.Nat),
  'points' : IDL.Nat,
});
export const ExcavationView = IDL.Record({
  'runPoints' : IDL.Nat,
  'diamonds' : IDL.Nat,
  'canSave' : IDL.Bool,
  'ifCollapse' : IDL.Nat,
  'nextPoints' : IDL.Nat,
  'chipId' : IDL.Nat,
  'picks' : IDL.Nat,
  'safePctX100' : IDL.Nat,
});
export const PlayerWeekResult = IDL.Record({
  'tiers' : IDL.Vec(IDL.Nat),
  'deepest' : IDL.Nat,
  'diamonds' : IDL.Nat,
  'collapses' : IDL.Nat,
  'best' : IDL.Nat,
  'chips' : IDL.Nat,
  'paid' : IDL.Nat,
  'week' : IDL.Nat,
  'received' : IDL.Nat,
  'drawWon' : IDL.Bool,
});
export const WeekStats = IDL.Record({
  'deepest' : IDL.Nat,
  'playTx' : IDL.Nat,
  'collapses' : IDL.Nat,
  'best' : IDL.Nat,
});
export const Dashboard = IDL.Record({
  'status' : WeekStatus,
  'tiers' : IDL.Vec(IDL.Nat),
  'balance' : IDL.Nat,
  'diamonds' : IDL.Nat,
  'chips' : IDL.Vec(ChipView),
  'open' : IDL.Opt(ExcavationView),
  'paid' : IDL.Nat,
  'week' : IDL.Nat,
  'history' : IDL.Vec(PlayerWeekResult),
  'totalDiamonds' : IDL.Nat,
  'stats' : WeekStats,
  'excavationsLeft' : IDL.Nat,
  'faucetRemaining' : IDL.Nat,
  'estimatedReceive' : IDL.Nat,
});
export const PickResult = IDL.Record({
  'collapsed' : IDL.Bool,
  'diamond' : IDL.Bool,
  'ended' : IDL.Bool,
  'pointsSaved' : IDL.Nat,
  'picks' : IDL.Nat,
  'excavation' : IDL.Opt(ExcavationView),
});
export const Result_2 = IDL.Variant({ 'ok' : PickResult, 'err' : IDL.Text });
export const PlayerRow = IDL.Record({
  'tiers' : IDL.Vec(IDL.Nat),
  'player' : IDL.Principal,
  'diamonds' : IDL.Nat,
  'chips' : IDL.Nat,
  'paid' : IDL.Nat,
  'avgX100' : IDL.Nat,
  'playing' : IDL.Bool,
  'estimatedReceive' : IDL.Nat,
});
export const Ranking = IDL.Record({
  'pot' : IDL.Nat,
  'status' : WeekStatus,
  'treasurePerChip' : IDL.Nat,
  'treasuryKeep' : IDL.Nat,
  'chips' : IDL.Nat,
  'week' : IDL.Nat,
  'totalDiamonds' : IDL.Nat,
  'players' : IDL.Vec(PlayerRow),
  'drawPrize' : IDL.Nat,
  'cutsX100' : IDL.Vec(IDL.Opt(IDL.Nat)),
});
export const Result = IDL.Variant({ 'ok' : ExcavationView, 'err' : IDL.Text });
export const TreasurySnapshot = IDL.Record({
  'ogy_usd' : IDL.Float64,
  'date' : IDL.Text,
  'wtn_usd' : IDL.Float64,
  'icp_usd' : IDL.Float64,
  'total_usd' : IDL.Float64,
  'ogy_amount' : IDL.Float64,
  'timestamp' : IDL.Nat64,
  'icp_amount' : IDL.Float64,
  'wtn_amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_7], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'adminListRoles' : IDL.Func([], [Result_6], ['query']),
  'adminSyncBootstrap' : IDL.Func([], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'gameAdminCloseWeek' : IDL.Func([], [Result_5], []),
  'gameAdminPayAndOpenNext' : IDL.Func([], [Result_1], []),
  'gameAdminRecoverClosing' : IDL.Func([], [Result_4], []),
  'gameAdminView' : IDL.Func([], [Result_3], ['query']),
  'gameBuyChips' : IDL.Func([IDL.Nat], [Result_1], []),
  'gameConfig' : IDL.Func([], [GameConfig], ['query']),
  'gameMyDashboard' : IDL.Func([], [Dashboard], ['query']),
  'gamePick' : IDL.Func([], [Result_2], []),
  'gameRanking' : IDL.Func([], [Ranking], ['query']),
  'gameRequestTestTokens' : IDL.Func([IDL.Nat], [Result_1], []),
  'gameSave' : IDL.Func([], [Result_1], []),
  'gameStartExcavation' : IDL.Func([], [Result], []),
  'gameWeeks' : IDL.Func([], [IDL.Vec(WeekSummary)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTreasuryHistory' : IDL.Func([], [IDL.Vec(TreasurySnapshot)], ['query']),
  'hasSnapshot' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveTreasurySnapshot' : IDL.Func([TreasurySnapshot], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, UserRole)),
    'err' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const WeekSummary = IDL.Record({
    'pot' : IDL.Nat,
    'treasurePerChip' : IDL.Nat,
    'treasuryKeep' : IDL.Nat,
    'chips' : IDL.Nat,
    'week' : IDL.Nat,
    'drawTicket' : IDL.Nat,
    'drawTickets' : IDL.Nat,
    'closedAt' : IDL.Int,
    'players' : IDL.Nat,
    'drawPrize' : IDL.Nat,
    'drawWinner' : IDL.Opt(IDL.Principal),
    'drawRandom' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({ 'ok' : WeekSummary, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const WeekStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'closing' : IDL.Null,
  });
  const PayoutConcept = IDL.Variant({ 'draw' : IDL.Null, 'prize' : IDL.Null });
  const Payout = IDL.Record({
    'to' : IDL.Principal,
    'concept' : PayoutConcept,
    'tiers' : IDL.Vec(IDL.Nat),
    'amount' : IDL.Nat,
  });
  const AdminView = IDL.Record({
    'status' : WeekStatus,
    'drawCarry' : IDL.Nat,
    'week' : IDL.Nat,
    'lastClose' : IDL.Opt(WeekSummary),
    'burned' : IDL.Nat,
    'payouts' : IDL.Vec(Payout),
    'treasury' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({ 'ok' : AdminView, 'err' : IDL.Text });
  const GameConfig = IDL.Record({
    'status' : WeekStatus,
    'mines' : IDL.Nat,
    'feeE8s' : IDL.Nat,
    'minChips' : IDL.Nat,
    'cells' : IDL.Nat,
    'pointsTable' : IDL.Vec(IDL.Nat),
    'week' : IDL.Nat,
    'minPlayers' : IDL.Nat,
    'treasuryBps' : IDL.Nat,
    'chipPriceE8s' : IDL.Nat,
    'tierCutsPct' : IDL.Vec(IDL.Nat),
    'safePicks' : IDL.Nat,
    'tierMultBps' : IDL.Vec(IDL.Nat),
    'faucetCapE8s' : IDL.Nat,
    'excavationsPerChip' : IDL.Nat,
    'drawBps' : IDL.Nat,
    'diamondBps' : IDL.Nat,
  });
  const TierIndex = IDL.Nat;
  const ChipView = IDL.Record({
    'id' : IDL.Nat,
    'diamonds' : IDL.Nat,
    'tier' : TierIndex,
    'used' : IDL.Nat,
    'avgX100' : IDL.Nat,
    'projectedX100' : IDL.Nat,
    'gapToNextX100' : IDL.Opt(IDL.Nat),
    'points' : IDL.Nat,
  });
  const ExcavationView = IDL.Record({
    'runPoints' : IDL.Nat,
    'diamonds' : IDL.Nat,
    'canSave' : IDL.Bool,
    'ifCollapse' : IDL.Nat,
    'nextPoints' : IDL.Nat,
    'chipId' : IDL.Nat,
    'picks' : IDL.Nat,
    'safePctX100' : IDL.Nat,
  });
  const PlayerWeekResult = IDL.Record({
    'tiers' : IDL.Vec(IDL.Nat),
    'deepest' : IDL.Nat,
    'diamonds' : IDL.Nat,
    'collapses' : IDL.Nat,
    'best' : IDL.Nat,
    'chips' : IDL.Nat,
    'paid' : IDL.Nat,
    'week' : IDL.Nat,
    'received' : IDL.Nat,
    'drawWon' : IDL.Bool,
  });
  const WeekStats = IDL.Record({
    'deepest' : IDL.Nat,
    'playTx' : IDL.Nat,
    'collapses' : IDL.Nat,
    'best' : IDL.Nat,
  });
  const Dashboard = IDL.Record({
    'status' : WeekStatus,
    'tiers' : IDL.Vec(IDL.Nat),
    'balance' : IDL.Nat,
    'diamonds' : IDL.Nat,
    'chips' : IDL.Vec(ChipView),
    'open' : IDL.Opt(ExcavationView),
    'paid' : IDL.Nat,
    'week' : IDL.Nat,
    'history' : IDL.Vec(PlayerWeekResult),
    'totalDiamonds' : IDL.Nat,
    'stats' : WeekStats,
    'excavationsLeft' : IDL.Nat,
    'faucetRemaining' : IDL.Nat,
    'estimatedReceive' : IDL.Nat,
  });
  const PickResult = IDL.Record({
    'collapsed' : IDL.Bool,
    'diamond' : IDL.Bool,
    'ended' : IDL.Bool,
    'pointsSaved' : IDL.Nat,
    'picks' : IDL.Nat,
    'excavation' : IDL.Opt(ExcavationView),
  });
  const Result_2 = IDL.Variant({ 'ok' : PickResult, 'err' : IDL.Text });
  const PlayerRow = IDL.Record({
    'tiers' : IDL.Vec(IDL.Nat),
    'player' : IDL.Principal,
    'diamonds' : IDL.Nat,
    'chips' : IDL.Nat,
    'paid' : IDL.Nat,
    'avgX100' : IDL.Nat,
    'playing' : IDL.Bool,
    'estimatedReceive' : IDL.Nat,
  });
  const Ranking = IDL.Record({
    'pot' : IDL.Nat,
    'status' : WeekStatus,
    'treasurePerChip' : IDL.Nat,
    'treasuryKeep' : IDL.Nat,
    'chips' : IDL.Nat,
    'week' : IDL.Nat,
    'totalDiamonds' : IDL.Nat,
    'players' : IDL.Vec(PlayerRow),
    'drawPrize' : IDL.Nat,
    'cutsX100' : IDL.Vec(IDL.Opt(IDL.Nat)),
  });
  const Result = IDL.Variant({ 'ok' : ExcavationView, 'err' : IDL.Text });
  const TreasurySnapshot = IDL.Record({
    'ogy_usd' : IDL.Float64,
    'date' : IDL.Text,
    'wtn_usd' : IDL.Float64,
    'icp_usd' : IDL.Float64,
    'total_usd' : IDL.Float64,
    'ogy_amount' : IDL.Float64,
    'timestamp' : IDL.Nat64,
    'icp_amount' : IDL.Float64,
    'wtn_amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_7], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'adminListRoles' : IDL.Func([], [Result_6], ['query']),
    'adminSyncBootstrap' : IDL.Func([], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'gameAdminCloseWeek' : IDL.Func([], [Result_5], []),
    'gameAdminPayAndOpenNext' : IDL.Func([], [Result_1], []),
    'gameAdminRecoverClosing' : IDL.Func([], [Result_4], []),
    'gameAdminView' : IDL.Func([], [Result_3], ['query']),
    'gameBuyChips' : IDL.Func([IDL.Nat], [Result_1], []),
    'gameConfig' : IDL.Func([], [GameConfig], ['query']),
    'gameMyDashboard' : IDL.Func([], [Dashboard], ['query']),
    'gamePick' : IDL.Func([], [Result_2], []),
    'gameRanking' : IDL.Func([], [Ranking], ['query']),
    'gameRequestTestTokens' : IDL.Func([IDL.Nat], [Result_1], []),
    'gameSave' : IDL.Func([], [Result_1], []),
    'gameStartExcavation' : IDL.Func([], [Result], []),
    'gameWeeks' : IDL.Func([], [IDL.Vec(WeekSummary)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTreasuryHistory' : IDL.Func([], [IDL.Vec(TreasurySnapshot)], ['query']),
    'hasSnapshot' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveTreasurySnapshot' : IDL.Func([TreasurySnapshot], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };