/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminView {
  'durationDays' : bigint,
  'staked' : bigint,
  'stakes' : Array<bigint>,
  'bankAccount' : [] | [Principal],
  'bank' : bigint,
  'fund' : bigint,
  'owed' : bigint,
  'pool' : bigint,
  'tournament' : bigint,
  'reserve' : bigint,
  'selfId' : [] | [Principal],
  'cycles' : bigint,
  'lastClose' : [] | [TournamentSummary],
  'withdrawable' : bigint,
  'bankAllowance' : bigint,
  'burned' : bigint,
  'realLedger' : boolean,
  'payouts' : Array<Payout>,
  'paused' : boolean,
  'endsAt' : bigint,
}
export interface AutoResult {
  'end' : EndResult,
  'pool' : bigint,
  'steps' : Array<AutoStep>,
}
export interface AutoStep {
  'collapsed' : boolean,
  'pick' : bigint,
  'diamond' : DiamondResult,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Dashboard {
  'stakes' : Array<bigint>,
  'balance' : bigint,
  'blocked' : boolean,
  'open' : [] | [ExcavationView],
  'pool' : bigint,
  'tournament' : bigint,
  'history' : Array<PlayerTournamentResult>,
  'credit' : bigint,
  'stats' : TournamentStats,
  'allowance' : bigint,
  'faucetRemaining' : bigint,
  'pendingPayout' : bigint,
  'paused' : boolean,
  'endsAt' : bigint,
}
export interface DiamondResult { 'won' : bigint, 'stage' : bigint }
export type EndKind = { 'maxed' : null } |
  { 'collapsed' : null } |
  { 'saved' : null };
export interface EndResult {
  'won' : bigint,
  'jackpotWon' : bigint,
  'balance' : bigint,
  'kind' : EndKind,
  'lost' : bigint,
  'credit' : bigint,
  'stake' : bigint,
  'gross' : bigint,
  'picks' : bigint,
  'charged' : bigint,
  'points' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExcavationView {
  'jackpotWon' : bigint,
  'runPoints' : bigint,
  'collapseGross' : bigint,
  'diamonds' : bigint,
  'nextGross' : bigint,
  'held' : bigint,
  'canSave' : boolean,
  'stake' : bigint,
  'runGross' : bigint,
  'picks' : bigint,
  'safePctX100' : bigint,
}
export interface FlagEntry { 'at' : bigint, 'player' : Principal }
export type GResult = { 'ok' : bigint } |
  { 'err' : string };
export type GResult_1 = { 'ok' : EndResult } |
  { 'err' : string };
export type GResult_2 = { 'ok' : PickResult } |
  { 'err' : string };
export type GResult_3 = { 'ok' : AutoResult } |
  { 'err' : string };
export type GResult_4 = { 'ok' : AdminView } |
  { 'err' : string };
export type GResult_5 = { 'ok' : null } |
  { 'err' : string };
export type GResult_6 = { 'ok' : SecurityView } |
  { 'err' : string };
export type GResult_7 = {
    'ok' : { 'paid' : bigint, 'remaining' : bigint, 'failed' : bigint }
  } |
  { 'err' : string };
export type GResult_8 = { 'ok' : Array<[Principal, UserRole]> } |
  { 'err' : string };
export interface GameConfig {
  'mines' : bigint,
  'ledgerId' : string,
  'stakeCapE8s' : bigint,
  'feeE8s' : bigint,
  'diamond1Bps' : bigint,
  'diamond2Bps' : bigint,
  'cells' : bigint,
  'pointsTable' : Array<bigint>,
  'maxPicks' : bigint,
  'payoutBps' : bigint,
  'safePicks' : bigint,
  'stakeMinE8s' : bigint,
  'faucetCapE8s' : bigint,
  'realLedger' : boolean,
  'diamond3PerGoldao' : bigint,
}
export interface JackpotWin {
  'at' : bigint,
  'player' : Principal,
  'tournament' : bigint,
  'stake' : bigint,
  'amount' : bigint,
}
export interface Payout {
  'id' : bigint,
  'to' : Principal,
  'paid' : boolean,
  'tournament' : bigint,
  'stamp' : bigint,
  'amount' : bigint,
}
export interface PickResult {
  'end' : [] | [EndResult],
  'collapsed' : boolean,
  'pool' : bigint,
  'diamond' : DiamondResult,
  'credit' : bigint,
  'picks' : bigint,
  'excavation' : [] | [ExcavationView],
}
export interface PlayerRow {
  'staked' : bigint,
  'jackpotWon' : bigint,
  'deepest' : bigint,
  'player' : Principal,
  'excavations' : bigint,
  'bestPoints' : bigint,
  'returned' : bigint,
}
export interface PlayerTournamentResult {
  'tournament' : bigint,
  'credit' : bigint,
  'stats' : TournamentStats,
  'payout' : bigint,
}
export interface Ranking {
  'staked' : bigint,
  'pool' : bigint,
  'tournament' : bigint,
  'players' : Array<PlayerRow>,
  'jackpots' : Array<JackpotWin>,
  'endsAt' : bigint,
}
export type Result_7 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SecurityView {
  'breakerWindowMin' : bigint,
  'breakerMax' : bigint,
  'haltCode' : bigint,
  'ledgerFails' : bigint,
  'haltedAt' : bigint,
  'accountingOk' : boolean,
  'halted' : boolean,
  'saturations' : bigint,
  'flagged' : Array<FlagEntry>,
}
export type StakeOption = { 'max' : null } |
  { 'mid' : null } |
  { 'min' : null };
export interface TournamentStats {
  'staked' : bigint,
  'jackpotWon' : bigint,
  'deepest' : bigint,
  'excavations' : bigint,
  'collapses' : bigint,
  'bestPoints' : bigint,
  'charged' : bigint,
  'returned' : bigint,
  'jackpots' : bigint,
}
export interface TournamentSummary {
  'staked' : bigint,
  'excavations' : bigint,
  'jackpotPaid' : bigint,
  'tournament' : bigint,
  'closedAt' : bigint,
  'players' : bigint,
  'forfeited' : bigint,
  'payoutTotal' : bigint,
  'returned' : bigint,
  'jackpots' : bigint,
}
export interface TreasurySnapshot {
  'ogy_usd' : number,
  'date' : string,
  'wtn_usd' : number,
  'icp_usd' : number,
  'total_usd' : number,
  'ogy_amount' : number,
  'timestamp' : bigint,
  'icp_amount' : number,
  'wtn_amount' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_7>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'adminListRoles' : ActorMethod<[], GResult_8>,
  'adminSyncBootstrap' : ActorMethod<[], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result__1>,
  'gameAdminAckAccounting' : ActorMethod<[], GResult_5>,
  'gameAdminCloseTournament' : ActorMethod<[], GResult_5>,
  'gameAdminHalt' : ActorMethod<[], GResult_5>,
  'gameAdminLedgerAllowance' : ActorMethod<[Principal, Principal], GResult>,
  'gameAdminLedgerBalance' : ActorMethod<[Principal], GResult>,
  'gameAdminPay' : ActorMethod<[], GResult_7>,
  'gameAdminRecordWithdrawal' : ActorMethod<[bigint], GResult>,
  'gameAdminRefreshBank' : ActorMethod<[], GResult>,
  'gameAdminReleaseBusy' : ActorMethod<[Principal], GResult_5>,
  'gameAdminResume' : ActorMethod<[], GResult_5>,
  'gameAdminSecurity' : ActorMethod<[], GResult_6>,
  'gameAdminSeedPool' : ActorMethod<[bigint], GResult>,
  'gameAdminSetBreaker' : ActorMethod<[bigint, bigint], GResult_5>,
  'gameAdminSetDuration' : ActorMethod<[bigint], GResult_5>,
  'gameAdminSetRealLedger' : ActorMethod<[Principal], GResult>,
  'gameAdminTestApprove' : ActorMethod<[bigint], GResult>,
  'gameAdminTestDeposit' : ActorMethod<[bigint], GResult>,
  'gameAdminUnblock' : ActorMethod<[Principal], GResult_5>,
  'gameAdminView' : ActorMethod<[], GResult_4>,
  'gameAdminWithdraw' : ActorMethod<[bigint], GResult>,
  'gameAuto' : ActorMethod<[StakeOption, bigint], GResult_3>,
  'gameConfig' : ActorMethod<[], GameConfig>,
  'gameMyDashboard' : ActorMethod<[], Dashboard>,
  'gamePick' : ActorMethod<[[] | [StakeOption]], GResult_2>,
  'gameRanking' : ActorMethod<[], Ranking>,
  'gameRequestTestTokens' : ActorMethod<[bigint], GResult>,
  'gameSave' : ActorMethod<[], GResult_1>,
  'gameTestApprove' : ActorMethod<[bigint], GResult>,
  'gameTournaments' : ActorMethod<[], Array<TournamentSummary>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Full history sorted by date ascending.
   */
  'getTreasuryHistory' : ActorMethod<[], Array<TreasurySnapshot>>,
  /**
   * / Check if a snapshot for the given date exists (cheap query).
   */
  'hasSnapshot' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Save a daily snapshot. Write-once per day — rejects if date exists.
   */
  'saveTreasurySnapshot' : ActorMethod<[TreasurySnapshot], boolean>,
  'schema' : ActorMethod<[], string>,
  'whoAmI' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
