/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminView {
  'status' : WeekStatus,
  'drawCarry' : bigint,
  'week' : bigint,
  'lastClose' : [] | [WeekSummary],
  'burned' : bigint,
  'payouts' : Array<Payout>,
  'treasury' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChipView {
  'id' : bigint,
  'diamonds' : bigint,
  'tier' : TierIndex,
  'used' : bigint,
  'avgX100' : bigint,
  'projectedX100' : bigint,
  'gapToNextX100' : [] | [bigint],
  'points' : bigint,
}
export interface Dashboard {
  'status' : WeekStatus,
  'tiers' : Array<bigint>,
  'balance' : bigint,
  'diamonds' : bigint,
  'chips' : Array<ChipView>,
  'open' : [] | [ExcavationView],
  'paid' : bigint,
  'week' : bigint,
  'history' : Array<PlayerWeekResult>,
  'totalDiamonds' : bigint,
  'stats' : WeekStats,
  'excavationsLeft' : bigint,
  'faucetRemaining' : bigint,
  'estimatedReceive' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExcavationView {
  'runPoints' : bigint,
  'diamonds' : bigint,
  'canSave' : boolean,
  'ifCollapse' : bigint,
  'nextPoints' : bigint,
  'chipId' : bigint,
  'picks' : bigint,
  'safePctX100' : bigint,
}
export interface GameConfig {
  'status' : WeekStatus,
  'mines' : bigint,
  'feeE8s' : bigint,
  'minChips' : bigint,
  'cells' : bigint,
  'pointsTable' : Array<bigint>,
  'week' : bigint,
  'minPlayers' : bigint,
  'treasuryBps' : bigint,
  'chipPriceE8s' : bigint,
  'tierCutsPct' : Array<bigint>,
  'safePicks' : bigint,
  'tierMultBps' : Array<bigint>,
  'faucetCapE8s' : bigint,
  'excavationsPerChip' : bigint,
  'drawBps' : bigint,
  'diamondBps' : bigint,
}
export interface Payout {
  'to' : Principal,
  'concept' : PayoutConcept,
  'tiers' : Array<bigint>,
  'amount' : bigint,
}
export type PayoutConcept = { 'draw' : null } |
  { 'prize' : null };
export interface PickResult {
  'collapsed' : boolean,
  'diamond' : boolean,
  'ended' : boolean,
  'pointsSaved' : bigint,
  'picks' : bigint,
  'excavation' : [] | [ExcavationView],
}
export interface PlayerRow {
  'tiers' : Array<bigint>,
  'player' : Principal,
  'diamonds' : bigint,
  'chips' : bigint,
  'paid' : bigint,
  'avgX100' : bigint,
  'playing' : boolean,
  'estimatedReceive' : bigint,
}
export interface PlayerWeekResult {
  'tiers' : Array<bigint>,
  'deepest' : bigint,
  'diamonds' : bigint,
  'collapses' : bigint,
  'best' : bigint,
  'chips' : bigint,
  'paid' : bigint,
  'week' : bigint,
  'received' : bigint,
  'drawWon' : boolean,
}
export interface Ranking {
  'pot' : bigint,
  'status' : WeekStatus,
  'treasurePerChip' : bigint,
  'treasuryKeep' : bigint,
  'chips' : bigint,
  'week' : bigint,
  'totalDiamonds' : bigint,
  'players' : Array<PlayerRow>,
  'drawPrize' : bigint,
  'cutsX100' : Array<[] | [bigint]>,
}
export type Result = { 'ok' : ExcavationView } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_2 = { 'ok' : PickResult } |
  { 'err' : string };
export type Result_3 = { 'ok' : AdminView } |
  { 'err' : string };
export type Result_4 = { 'ok' : null } |
  { 'err' : string };
export type Result_5 = { 'ok' : WeekSummary } |
  { 'err' : string };
export type Result_6 = { 'ok' : Array<[Principal, UserRole]> } |
  { 'err' : string };
export type Result_7 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type TierIndex = bigint;
export interface TreasurySnapshot {
  'ogy_usd' : number,
  'date' : string,
  'wtn_usd' : number,
  'icp_usd' : number,
  'total_usd' : number,
  'ogy_amount' : number,
  'timestamp' : bigint,
  'icp_amount' : number,
  'wtn_amount' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WeekStats {
  'deepest' : bigint,
  'playTx' : bigint,
  'collapses' : bigint,
  'best' : bigint,
}
export type WeekStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'closing' : null };
export interface WeekSummary {
  'pot' : bigint,
  'treasurePerChip' : bigint,
  'treasuryKeep' : bigint,
  'chips' : bigint,
  'week' : bigint,
  'drawTicket' : bigint,
  'drawTickets' : bigint,
  'closedAt' : bigint,
  'players' : bigint,
  'drawPrize' : bigint,
  'drawWinner' : [] | [Principal],
  'drawRandom' : bigint,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_7>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Lists every principal that has a role. Admin only.
   */
  'adminListRoles' : ActorMethod<[], Result_6>,
  /**
   * / Syncs the app-wide admin role for the hardcoded bootstrap principals (Game.BOOTSTRAP_ADMINS).
   * / Returns true only when the caller is one of them; does nothing otherwise.
   */
  'adminSyncBootstrap' : ActorMethod<[], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Closes the week: saves open excavations, auto-plays the remaining ones
   * / saving at 3, ranks chips, computes payouts and runs the diamond draw.
   */
  'gameAdminCloseWeek' : ActorMethod<[], Result_5>,
  /**
   * / Credits all payouts (simulated), archives the week and opens the next one.
   */
  'gameAdminPayAndOpenNext' : ActorMethod<[], Result_1>,
  /**
   * / Recovery: if a close was interrupted (status stuck in #closing), reopens the week
   * / so the admin can run the close again. Open excavations were already saved.
   */
  'gameAdminRecoverClosing' : ActorMethod<[], Result_4>,
  'gameAdminView' : ActorMethod<[], Result_3>,
  /**
   * / Buys chips: sends n x 1,000 to the treasury + 10 fee.
   */
  'gameBuyChips' : ActorMethod<[bigint], Result_1>,
  'gameConfig' : ActorMethod<[], GameConfig>,
  'gameMyDashboard' : ActorMethod<[], Dashboard>,
  /**
   * / One pick. Calls raw_rand to resolve collapse (from the 3rd pick) and diamond.
   */
  'gamePick' : ActorMethod<[], Result_2>,
  'gameRanking' : ActorMethod<[], Ranking>,
  /**
   * / Test GOLDAO: up to FAUCET_CAP per principal per week.
   */
  'gameRequestTestTokens' : ActorMethod<[bigint], Result_1>,
  'gameSave' : ActorMethod<[], Result_1>,
  'gameStartExcavation' : ActorMethod<[], Result>,
  'gameWeeks' : ActorMethod<[], Array<WeekSummary>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Full history sorted by date ascending.
   */
  'getTreasuryHistory' : ActorMethod<[], Array<TreasurySnapshot>>,
  /**
   * / Check if a snapshot for the given date exists (cheap query).
   */
  'hasSnapshot' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Save a daily snapshot. Write-once per day — rejects if date exists.
   */
  'saveTreasurySnapshot' : ActorMethod<[TreasurySnapshot], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Returns the caller's principal as text.
   */
  'whoAmI' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];