/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminView {
  'durationDays' : bigint,
  'staked' : bigint,
  'stakes' : Array<bigint>,
  'top10' : bigint,
  'smallBalances' : bigint,
  'toCollect' : bigint,
  'bankAccount' : [] | [Principal],
  'bank' : bigint,
  'fund' : bigint,
  'owed' : bigint,
  'pool' : bigint,
  'tournament' : bigint,
  'reserve' : bigint,
  'selfId' : [] | [Principal],
  'cycles' : bigint,
  'lastClose' : [] | [TournamentSummary],
  'withdrawable' : bigint,
  'smallPlayers' : bigint,
  'bankAllowance' : bigint,
  'burned' : bigint,
  'heldJackpots' : bigint,
  'toCollectPlayers' : bigint,
  'realLedger' : boolean,
  'payouts' : Array<Payout>,
  'paused' : boolean,
  'unpaidPayouts' : bigint,
  'endsAt' : bigint,
}
export interface AutoResult {
  'end' : EndResult,
  'pool' : bigint,
  'steps' : Array<AutoStep>,
}
export interface AutoStep {
  'collapsed' : boolean,
  'pick' : bigint,
  'diamond' : DiamondResult,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Dashboard {
  'top10Pool' : bigint,
  'top10Rank' : bigint,
  'stakes' : Array<bigint>,
  'top10Prize' : bigint,
  'balance' : bigint,
  'open' : [] | [ExcavationView],
  'pool' : bigint,
  'tournament' : bigint,
  'history' : Array<PlayerTournamentResult>,
  'credit' : bigint,
  'stats' : TournamentStats,
  'bestReturn' : bigint,
  'allowance' : bigint,
  'top10Entry' : bigint,
  'pendingPayout' : bigint,
  'paused' : boolean,
  'endsAt' : bigint,
}
export interface DiamondResult { 'won' : bigint, 'stage' : bigint }
export type EndKind = { 'maxed' : null } |
  { 'collapsed' : null } |
  { 'saved' : null };
export interface EndResult {
  'won' : bigint,
  'jackpotWon' : bigint,
  'balance' : bigint,
  'kind' : EndKind,
  'lost' : bigint,
  'credit' : bigint,
  'stake' : bigint,
  'gross' : bigint,
  'picks' : bigint,
  'points' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExcavationView {
  'jackpotWon' : bigint,
  'runPoints' : bigint,
  'collapseGross' : bigint,
  'diamonds' : bigint,
  'nextGross' : bigint,
  'held' : bigint,
  'canSave' : boolean,
  'stake' : bigint,
  'runGross' : bigint,
  'picks' : bigint,
  'safePctX100' : bigint,
}
export interface FaucetConfig {
  'presets' : Array<bigint>,
  'usedE8s' : bigint,
  'enabled' : boolean,
  'capE8s' : bigint,
}
export interface GameConfig {
  'mines' : bigint,
  'loadMax' : bigint,
  'loadMin' : bigint,
  'top10Bps' : bigint,
  'ledgerId' : string,
  'top10Weights' : Array<bigint>,
  'diamond2PerGoldao' : bigint,
  'stakeCapE8s' : bigint,
  'feeE8s' : bigint,
  'diamond1Bps' : bigint,
  'cells' : bigint,
  'pointsTable' : Array<bigint>,
  'miniBps' : bigint,
  'creditCapE8s' : bigint,
  'maxPicks' : bigint,
  'diamond3Odds' : bigint,
  'top10MinVolumeE8s' : bigint,
  'poolSeedMaxE8s' : bigint,
  'poolSeedE8s' : bigint,
  'payoutBps' : bigint,
  'safePicks' : bigint,
  'minPayoutE8s' : bigint,
  'stakeMinE8s' : bigint,
  'realLedger' : boolean,
}
export interface GameSummary {
  'top10Pool' : bigint,
  'staked' : bigint,
  'totalPlayers' : bigint,
  'pool' : bigint,
  'tournament' : bigint,
  'paused' : boolean,
  'endsAt' : bigint,
}
export interface JackpotWin {
  'at' : bigint,
  'player' : Principal,
  'tournament' : bigint,
  'stake' : bigint,
  'amount' : bigint,
}
export interface PastStats {
  'staked' : bigint,
  'jackpotWon' : bigint,
  'excavations' : bigint,
  'returned' : bigint,
}
export interface Payout {
  'id' : bigint,
  'to' : Principal,
  'paid' : boolean,
  'txId' : [] | [bigint],
  'tournament' : bigint,
  'uncertain' : boolean,
  'stamp' : bigint,
  'amount' : bigint,
  'paidAt' : bigint,
}
export interface PickResult {
  'end' : [] | [EndResult],
  'collapsed' : boolean,
  'pool' : bigint,
  'diamond' : DiamondResult,
  'credit' : bigint,
  'picks' : bigint,
  'excavation' : [] | [ExcavationView],
}
export interface PlayerRow {
  'net' : bigint,
  'pos' : bigint,
  'staked' : bigint,
  'jackpotWon' : bigint,
  'player' : Principal,
  'excavations' : bigint,
  'rank' : bigint,
  'bestReturn' : bigint,
  'prize' : bigint,
  'returned' : bigint,
}
export interface PlayerTournamentResult {
  'tournament' : bigint,
  'credit' : bigint,
  'stats' : PastStats,
  'payout' : bigint,
}
export interface RankingPage {
  'totalPlayers' : bigint,
  'mine' : [] | [PlayerRow],
  'page' : bigint,
  'rows' : Array<PlayerRow>,
  'sort' : RankingSort,
  'pageSize' : bigint,
  'lastTop10' : Array<TopPrize>,
  'jackpots' : Array<JackpotWin>,
}
export type RankingSort = { 'net' : null } |
  { 'jackpot' : null } |
  { 'volume' : null } |
  { 'bestPrize' : null };
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export type Result_1 = { 'ok' : EndResult } |
  { 'err' : string };
export type Result_10 = {
    'ok' : { 'paid' : bigint, 'remaining' : bigint, 'failed' : bigint }
  } |
  { 'err' : string };
export type Result_11 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_12 = { 'ok' : Array<[Principal, UserRole]> } |
  { 'err' : string };
export type Result_13 = { 'ok' : null } |
  { 'err' : Error };
export type Result_2 = { 'ok' : PickResult } |
  { 'err' : string };
export type Result_3 = { 'ok' : AutoResult } |
  { 'err' : string };
export type Result_4 = { 'ok' : AdminView } |
  { 'err' : string };
export type Result_5 = { 'ok' : null } |
  { 'err' : string };
export type Result_6 = { 'ok' : SecurityLogView } |
  { 'err' : string };
export type Result_7 = { 'ok' : SecurityView } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<Payout> } |
  { 'err' : string };
export type Result_9 = { 'ok' : [] | [bigint] } |
  { 'err' : string };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SecurityDay {
  'day' : bigint,
  'events' : bigint,
  'attention' : bigint,
}
export interface SecurityEvent {
  'at' : bigint,
  'title' : string,
  'code' : string,
  'count' : bigint,
  'lastAt' : bigint,
  'description' : string,
  'level' : SecurityLevel,
}
export type SecurityLevel = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface SecurityLogView {
  'day' : bigint,
  'days' : Array<SecurityDay>,
  'events' : Array<SecurityEvent>,
}
export interface SecurityView {
  'haltCode' : bigint,
  'ledgerFails' : bigint,
  'haltedAt' : bigint,
  'accountingOk' : boolean,
  'halted' : boolean,
  'saturations' : bigint,
}
export type StakeOption = { 'max' : null } |
  { 'mid' : null } |
  { 'min' : null };
export interface TopPrize {
  'player' : Principal,
  'rank' : bigint,
  'tournament' : bigint,
  'volume' : bigint,
  'prize' : bigint,
}
export interface TournamentStats {
  'staked' : bigint,
  'minis' : bigint,
  'jackpotWon' : bigint,
  'deepest' : bigint,
  'excavations' : bigint,
  'collapses' : bigint,
  'miniWon' : bigint,
  'returned' : bigint,
  'jackpots' : bigint,
}
export interface TournamentSummary {
  'staked' : bigint,
  'minis' : bigint,
  'miniPaid' : bigint,
  'excavations' : bigint,
  'jackpotPaid' : bigint,
  'tournament' : bigint,
  'closedAt' : bigint,
  'players' : bigint,
  'forfeited' : bigint,
  'payoutTotal' : bigint,
  'returned' : bigint,
  'jackpots' : bigint,
}
export interface TreasurySnapshot {
  'ogy_usd' : number,
  'date' : string,
  'wtn_usd' : number,
  'icp_usd' : number,
  'total_usd' : number,
  'ogy_amount' : number,
  'timestamp' : bigint,
  'icp_amount' : number,
  'wtn_amount' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type WithdrawKind = { 'all' : null } |
  { 'available' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_13>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'adminListRoles' : ActorMethod<[], Result_12>,
  'adminSyncBootstrap' : ActorMethod<[], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result__1>,
  'gameAdminAckAccounting' : ActorMethod<[], Result_5>,
  'gameAdminChangeLedger' : ActorMethod<[], Result>,
  'gameAdminCheckPay' : ActorMethod<[], Result_5>,
  'gameAdminCheckWithdraw' : ActorMethod<[WithdrawKind], Result_5>,
  'gameAdminCloseAll' : ActorMethod<[], Result_5>,
  'gameAdminCloseTournament' : ActorMethod<[], Result_5>,
  'gameAdminEnsureConnected' : ActorMethod<[], Result_11>,
  'gameAdminHalt' : ActorMethod<[], Result_5>,
  'gameAdminLedgerAllowance' : ActorMethod<[Principal, Principal], Result>,
  'gameAdminLedgerBalance' : ActorMethod<[Principal], Result>,
  'gameAdminMarkPaid' : ActorMethod<[bigint, bigint], Result_5>,
  'gameAdminPay' : ActorMethod<[bigint], Result_10>,
  'gameAdminPayOne' : ActorMethod<[bigint, boolean], Result_9>,
  'gameAdminPayouts' : ActorMethod<[bigint], Result_8>,
  'gameAdminRefreshBank' : ActorMethod<[], Result>,
  'gameAdminReleaseBusy' : ActorMethod<[Principal], Result_5>,
  'gameAdminResume' : ActorMethod<[], Result_5>,
  'gameAdminSecurity' : ActorMethod<[], Result_7>,
  'gameAdminSecurityLog' : ActorMethod<[bigint], Result_6>,
  'gameAdminSeedPool' : ActorMethod<[bigint], Result>,
  'gameAdminSetDuration' : ActorMethod<[bigint], Result_5>,
  'gameAdminView' : ActorMethod<[], Result_4>,
  'gameAdminWithdraw' : ActorMethod<[WithdrawKind], Result>,
  'gameAuto' : ActorMethod<[StakeOption, bigint, bigint], Result_3>,
  'gameBurned' : ActorMethod<[], bigint>,
  'gameConfig' : ActorMethod<[], GameConfig>,
  'gameLoadCredit' : ActorMethod<[bigint], Result>,
  'gameMyDashboard' : ActorMethod<[], Dashboard>,
  'gamePick' : ActorMethod<[[] | [StakeOption], bigint, bigint], Result_2>,
  'gameRankingPage' : ActorMethod<[RankingSort, bigint], RankingPage>,
  'gameSave' : ActorMethod<[], Result_1>,
  'gameSummary' : ActorMethod<[], GameSummary>,
  'gameTournaments' : ActorMethod<[], Array<TournamentSummary>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Full history sorted by date ascending.
   */
  'getTreasuryHistory' : ActorMethod<[], Array<TreasurySnapshot>>,
  /**
   * / Check if a snapshot for the given date exists (cheap query).
   */
  'hasSnapshot' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Save a daily snapshot. Write-once per day, only for today's date (UTC), validated in the lib.
   */
  'saveTreasurySnapshot' : ActorMethod<[TreasurySnapshot], boolean>,
  'schema' : ActorMethod<[], string>,
  'testFaucetClaim' : ActorMethod<[bigint], Result>,
  'testFaucetConfig' : ActorMethod<[], FaucetConfig>,
  'whoAmI' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
