/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, UserRole)),
  'err' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result_7 = IDL.Variant({
  'ok' : IDL.Record({
    'paid' : IDL.Nat,
    'remaining' : IDL.Nat,
    'failed' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const SecurityView = IDL.Record({
  'haltCode' : IDL.Nat,
  'ledgerFails' : IDL.Nat,
  'haltedAt' : IDL.Int,
  'accountingOk' : IDL.Bool,
  'halted' : IDL.Bool,
  'saturations' : IDL.Nat,
});
export const Result_6 = IDL.Variant({ 'ok' : SecurityView, 'err' : IDL.Text });
export const TournamentSummary = IDL.Record({
  'staked' : IDL.Nat,
  'excavations' : IDL.Nat,
  'jackpotPaid' : IDL.Nat,
  'tournament' : IDL.Nat,
  'closedAt' : IDL.Int,
  'players' : IDL.Nat,
  'forfeited' : IDL.Nat,
  'payoutTotal' : IDL.Nat,
  'returned' : IDL.Nat,
  'jackpots' : IDL.Nat,
});
export const Payout = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'paid' : IDL.Bool,
  'tournament' : IDL.Nat,
  'stamp' : IDL.Nat64,
  'amount' : IDL.Nat,
});
export const AdminView = IDL.Record({
  'durationDays' : IDL.Nat,
  'staked' : IDL.Nat,
  'stakes' : IDL.Vec(IDL.Nat),
  'top10' : IDL.Nat,
  'smallBalances' : IDL.Nat,
  'toCollect' : IDL.Nat,
  'bankAccount' : IDL.Opt(IDL.Principal),
  'bank' : IDL.Nat,
  'fund' : IDL.Int,
  'owed' : IDL.Nat,
  'pool' : IDL.Nat,
  'tournament' : IDL.Nat,
  'reserve' : IDL.Nat,
  'selfId' : IDL.Opt(IDL.Principal),
  'cycles' : IDL.Nat,
  'lastClose' : IDL.Opt(TournamentSummary),
  'withdrawable' : IDL.Nat,
  'smallPlayers' : IDL.Nat,
  'bankAllowance' : IDL.Nat,
  'burned' : IDL.Nat,
  'heldJackpots' : IDL.Nat,
  'toCollectPlayers' : IDL.Nat,
  'realLedger' : IDL.Bool,
  'payouts' : IDL.Vec(Payout),
  'paused' : IDL.Bool,
  'unpaidPayouts' : IDL.Nat,
  'endsAt' : IDL.Int,
});
export const Result_4 = IDL.Variant({ 'ok' : AdminView, 'err' : IDL.Text });
export const WithdrawKind = IDL.Variant({
  'all' : IDL.Null,
  'available' : IDL.Null,
});
export const StakeOption = IDL.Variant({
  'max' : IDL.Null,
  'mid' : IDL.Null,
  'min' : IDL.Null,
});
export const EndKind = IDL.Variant({
  'maxed' : IDL.Null,
  'collapsed' : IDL.Null,
  'saved' : IDL.Null,
});
export const EndResult = IDL.Record({
  'won' : IDL.Nat,
  'jackpotWon' : IDL.Nat,
  'balance' : IDL.Nat,
  'kind' : EndKind,
  'lost' : IDL.Nat,
  'credit' : IDL.Nat,
  'stake' : IDL.Nat,
  'gross' : IDL.Nat,
  'picks' : IDL.Nat,
  'points' : IDL.Nat,
});
export const DiamondResult = IDL.Record({ 'won' : IDL.Nat, 'stage' : IDL.Nat });
export const AutoStep = IDL.Record({
  'collapsed' : IDL.Bool,
  'pick' : IDL.Nat,
  'diamond' : DiamondResult,
});
export const AutoResult = IDL.Record({
  'end' : EndResult,
  'pool' : IDL.Nat,
  'steps' : IDL.Vec(AutoStep),
});
export const Result_3 = IDL.Variant({ 'ok' : AutoResult, 'err' : IDL.Text });
export const GameConfig = IDL.Record({
  'mines' : IDL.Nat,
  'loadMax' : IDL.Nat,
  'loadMin' : IDL.Nat,
  'top10Bps' : IDL.Nat,
  'ledgerId' : IDL.Text,
  'top10Weights' : IDL.Vec(IDL.Nat),
  'stakeCapE8s' : IDL.Nat,
  'feeE8s' : IDL.Nat,
  'diamond1Bps' : IDL.Nat,
  'diamond2Bps' : IDL.Nat,
  'cells' : IDL.Nat,
  'pointsTable' : IDL.Vec(IDL.Nat),
  'creditCapE8s' : IDL.Nat,
  'maxPicks' : IDL.Nat,
  'top10MinVolumeE8s' : IDL.Nat,
  'payoutBps' : IDL.Nat,
  'safePicks' : IDL.Nat,
  'minPayoutE8s' : IDL.Nat,
  'stakeMinE8s' : IDL.Nat,
  'faucetCapE8s' : IDL.Nat,
  'realLedger' : IDL.Bool,
  'diamond3PerGoldao' : IDL.Nat,
});
export const ExcavationView = IDL.Record({
  'jackpotWon' : IDL.Nat,
  'runPoints' : IDL.Nat,
  'collapseGross' : IDL.Nat,
  'diamonds' : IDL.Nat,
  'nextGross' : IDL.Nat,
  'held' : IDL.Nat,
  'canSave' : IDL.Bool,
  'stake' : IDL.Nat,
  'runGross' : IDL.Nat,
  'picks' : IDL.Nat,
  'safePctX100' : IDL.Nat,
});
export const TournamentStats = IDL.Record({
  'staked' : IDL.Nat,
  'jackpotWon' : IDL.Nat,
  'deepest' : IDL.Nat,
  'excavations' : IDL.Nat,
  'collapses' : IDL.Nat,
  'bestPoints' : IDL.Nat,
  'charged' : IDL.Nat,
  'returned' : IDL.Nat,
  'jackpots' : IDL.Nat,
});
export const PlayerTournamentResult = IDL.Record({
  'tournament' : IDL.Nat,
  'credit' : IDL.Nat,
  'stats' : TournamentStats,
  'payout' : IDL.Nat,
});
export const Dashboard = IDL.Record({
  'top10Pool' : IDL.Nat,
  'top10Rank' : IDL.Nat,
  'stakes' : IDL.Vec(IDL.Nat),
  'top10Prize' : IDL.Nat,
  'balance' : IDL.Nat,
  'open' : IDL.Opt(ExcavationView),
  'pool' : IDL.Nat,
  'tournament' : IDL.Nat,
  'history' : IDL.Vec(PlayerTournamentResult),
  'credit' : IDL.Nat,
  'stats' : TournamentStats,
  'bestReturn' : IDL.Nat,
  'allowance' : IDL.Nat,
  'faucetRemaining' : IDL.Nat,
  'top10Entry' : IDL.Nat,
  'pendingPayout' : IDL.Nat,
  'paused' : IDL.Bool,
  'endsAt' : IDL.Int,
});
export const PickResult = IDL.Record({
  'end' : IDL.Opt(EndResult),
  'collapsed' : IDL.Bool,
  'pool' : IDL.Nat,
  'diamond' : DiamondResult,
  'credit' : IDL.Nat,
  'picks' : IDL.Nat,
  'excavation' : IDL.Opt(ExcavationView),
});
export const Result_2 = IDL.Variant({ 'ok' : PickResult, 'err' : IDL.Text });
export const TopPrize = IDL.Record({
  'player' : IDL.Principal,
  'rank' : IDL.Nat,
  'tournament' : IDL.Nat,
  'volume' : IDL.Nat,
  'prize' : IDL.Nat,
});
export const PlayerRow = IDL.Record({
  'staked' : IDL.Nat,
  'jackpotWon' : IDL.Nat,
  'deepest' : IDL.Nat,
  'player' : IDL.Principal,
  'excavations' : IDL.Nat,
  'rank' : IDL.Nat,
  'bestPoints' : IDL.Nat,
  'prize' : IDL.Nat,
  'returned' : IDL.Nat,
});
export const JackpotWin = IDL.Record({
  'at' : IDL.Int,
  'player' : IDL.Principal,
  'tournament' : IDL.Nat,
  'stake' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Ranking = IDL.Record({
  'top10Pool' : IDL.Nat,
  'staked' : IDL.Nat,
  'pool' : IDL.Nat,
  'tournament' : IDL.Nat,
  'lastTop10' : IDL.Vec(TopPrize),
  'players' : IDL.Vec(PlayerRow),
  'jackpots' : IDL.Vec(JackpotWin),
  'endsAt' : IDL.Int,
});
export const Result_1 = IDL.Variant({ 'ok' : EndResult, 'err' : IDL.Text });
export const TreasurySnapshot = IDL.Record({
  'ogy_usd' : IDL.Float64,
  'date' : IDL.Text,
  'wtn_usd' : IDL.Float64,
  'icp_usd' : IDL.Float64,
  'total_usd' : IDL.Float64,
  'ogy_amount' : IDL.Float64,
  'timestamp' : IDL.Nat64,
  'icp_amount' : IDL.Float64,
  'wtn_amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_9], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'adminListRoles' : IDL.Func([], [Result_8], ['query']),
  'adminSyncBootstrap' : IDL.Func([], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'gameAdminAckAccounting' : IDL.Func([], [Result_5], []),
  'gameAdminCloseAll' : IDL.Func([], [Result_5], []),
  'gameAdminCloseTournament' : IDL.Func([], [Result_5], []),
  'gameAdminHalt' : IDL.Func([], [Result_5], []),
  'gameAdminLedgerAllowance' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [Result],
      [],
    ),
  'gameAdminLedgerBalance' : IDL.Func([IDL.Principal], [Result], []),
  'gameAdminPay' : IDL.Func([], [Result_7], []),
  'gameAdminRefreshBank' : IDL.Func([], [Result], []),
  'gameAdminReleaseBusy' : IDL.Func([IDL.Principal], [Result_5], []),
  'gameAdminResume' : IDL.Func([], [Result_5], []),
  'gameAdminSecurity' : IDL.Func([], [Result_6], ['query']),
  'gameAdminSeedPool' : IDL.Func([IDL.Nat], [Result], []),
  'gameAdminSetDuration' : IDL.Func([IDL.Nat], [Result_5], []),
  'gameAdminSetRealLedger' : IDL.Func([IDL.Principal], [Result], []),
  'gameAdminTestDeposit' : IDL.Func([IDL.Nat], [Result], []),
  'gameAdminView' : IDL.Func([], [Result_4], ['query']),
  'gameAdminWithdraw' : IDL.Func([WithdrawKind], [Result], []),
  'gameAuto' : IDL.Func([StakeOption, IDL.Nat], [Result_3], []),
  'gameBurned' : IDL.Func([], [IDL.Nat], ['query']),
  'gameConfig' : IDL.Func([], [GameConfig], ['query']),
  'gameLoadCredit' : IDL.Func([IDL.Nat], [Result], []),
  'gameMyDashboard' : IDL.Func([], [Dashboard], ['query']),
  'gamePick' : IDL.Func([IDL.Opt(StakeOption)], [Result_2], []),
  'gameRanking' : IDL.Func([], [Ranking], ['query']),
  'gameRequestTestTokens' : IDL.Func([IDL.Nat], [Result], []),
  'gameSave' : IDL.Func([], [Result_1], []),
  'gameTestApprove' : IDL.Func([IDL.Nat], [Result], []),
  'gameTournaments' : IDL.Func([], [IDL.Vec(TournamentSummary)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTreasuryHistory' : IDL.Func([], [IDL.Vec(TreasurySnapshot)], ['query']),
  'hasSnapshot' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveTreasurySnapshot' : IDL.Func([TreasurySnapshot], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, UserRole)),
    'err' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Record({
      'paid' : IDL.Nat,
      'remaining' : IDL.Nat,
      'failed' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const SecurityView = IDL.Record({
    'haltCode' : IDL.Nat,
    'ledgerFails' : IDL.Nat,
    'haltedAt' : IDL.Int,
    'accountingOk' : IDL.Bool,
    'halted' : IDL.Bool,
    'saturations' : IDL.Nat,
  });
  const Result_6 = IDL.Variant({ 'ok' : SecurityView, 'err' : IDL.Text });
  const TournamentSummary = IDL.Record({
    'staked' : IDL.Nat,
    'excavations' : IDL.Nat,
    'jackpotPaid' : IDL.Nat,
    'tournament' : IDL.Nat,
    'closedAt' : IDL.Int,
    'players' : IDL.Nat,
    'forfeited' : IDL.Nat,
    'payoutTotal' : IDL.Nat,
    'returned' : IDL.Nat,
    'jackpots' : IDL.Nat,
  });
  const Payout = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'paid' : IDL.Bool,
    'tournament' : IDL.Nat,
    'stamp' : IDL.Nat64,
    'amount' : IDL.Nat,
  });
  const AdminView = IDL.Record({
    'durationDays' : IDL.Nat,
    'staked' : IDL.Nat,
    'stakes' : IDL.Vec(IDL.Nat),
    'top10' : IDL.Nat,
    'smallBalances' : IDL.Nat,
    'toCollect' : IDL.Nat,
    'bankAccount' : IDL.Opt(IDL.Principal),
    'bank' : IDL.Nat,
    'fund' : IDL.Int,
    'owed' : IDL.Nat,
    'pool' : IDL.Nat,
    'tournament' : IDL.Nat,
    'reserve' : IDL.Nat,
    'selfId' : IDL.Opt(IDL.Principal),
    'cycles' : IDL.Nat,
    'lastClose' : IDL.Opt(TournamentSummary),
    'withdrawable' : IDL.Nat,
    'smallPlayers' : IDL.Nat,
    'bankAllowance' : IDL.Nat,
    'burned' : IDL.Nat,
    'heldJackpots' : IDL.Nat,
    'toCollectPlayers' : IDL.Nat,
    'realLedger' : IDL.Bool,
    'payouts' : IDL.Vec(Payout),
    'paused' : IDL.Bool,
    'unpaidPayouts' : IDL.Nat,
    'endsAt' : IDL.Int,
  });
  const Result_4 = IDL.Variant({ 'ok' : AdminView, 'err' : IDL.Text });
  const WithdrawKind = IDL.Variant({
    'all' : IDL.Null,
    'available' : IDL.Null,
  });
  const StakeOption = IDL.Variant({
    'max' : IDL.Null,
    'mid' : IDL.Null,
    'min' : IDL.Null,
  });
  const EndKind = IDL.Variant({
    'maxed' : IDL.Null,
    'collapsed' : IDL.Null,
    'saved' : IDL.Null,
  });
  const EndResult = IDL.Record({
    'won' : IDL.Nat,
    'jackpotWon' : IDL.Nat,
    'balance' : IDL.Nat,
    'kind' : EndKind,
    'lost' : IDL.Nat,
    'credit' : IDL.Nat,
    'stake' : IDL.Nat,
    'gross' : IDL.Nat,
    'picks' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const DiamondResult = IDL.Record({ 'won' : IDL.Nat, 'stage' : IDL.Nat });
  const AutoStep = IDL.Record({
    'collapsed' : IDL.Bool,
    'pick' : IDL.Nat,
    'diamond' : DiamondResult,
  });
  const AutoResult = IDL.Record({
    'end' : EndResult,
    'pool' : IDL.Nat,
    'steps' : IDL.Vec(AutoStep),
  });
  const Result_3 = IDL.Variant({ 'ok' : AutoResult, 'err' : IDL.Text });
  const GameConfig = IDL.Record({
    'mines' : IDL.Nat,
    'loadMax' : IDL.Nat,
    'loadMin' : IDL.Nat,
    'top10Bps' : IDL.Nat,
    'ledgerId' : IDL.Text,
    'top10Weights' : IDL.Vec(IDL.Nat),
    'stakeCapE8s' : IDL.Nat,
    'feeE8s' : IDL.Nat,
    'diamond1Bps' : IDL.Nat,
    'diamond2Bps' : IDL.Nat,
    'cells' : IDL.Nat,
    'pointsTable' : IDL.Vec(IDL.Nat),
    'creditCapE8s' : IDL.Nat,
    'maxPicks' : IDL.Nat,
    'top10MinVolumeE8s' : IDL.Nat,
    'payoutBps' : IDL.Nat,
    'safePicks' : IDL.Nat,
    'minPayoutE8s' : IDL.Nat,
    'stakeMinE8s' : IDL.Nat,
    'faucetCapE8s' : IDL.Nat,
    'realLedger' : IDL.Bool,
    'diamond3PerGoldao' : IDL.Nat,
  });
  const ExcavationView = IDL.Record({
    'jackpotWon' : IDL.Nat,
    'runPoints' : IDL.Nat,
    'collapseGross' : IDL.Nat,
    'diamonds' : IDL.Nat,
    'nextGross' : IDL.Nat,
    'held' : IDL.Nat,
    'canSave' : IDL.Bool,
    'stake' : IDL.Nat,
    'runGross' : IDL.Nat,
    'picks' : IDL.Nat,
    'safePctX100' : IDL.Nat,
  });
  const TournamentStats = IDL.Record({
    'staked' : IDL.Nat,
    'jackpotWon' : IDL.Nat,
    'deepest' : IDL.Nat,
    'excavations' : IDL.Nat,
    'collapses' : IDL.Nat,
    'bestPoints' : IDL.Nat,
    'charged' : IDL.Nat,
    'returned' : IDL.Nat,
    'jackpots' : IDL.Nat,
  });
  const PlayerTournamentResult = IDL.Record({
    'tournament' : IDL.Nat,
    'credit' : IDL.Nat,
    'stats' : TournamentStats,
    'payout' : IDL.Nat,
  });
  const Dashboard = IDL.Record({
    'top10Pool' : IDL.Nat,
    'top10Rank' : IDL.Nat,
    'stakes' : IDL.Vec(IDL.Nat),
    'top10Prize' : IDL.Nat,
    'balance' : IDL.Nat,
    'open' : IDL.Opt(ExcavationView),
    'pool' : IDL.Nat,
    'tournament' : IDL.Nat,
    'history' : IDL.Vec(PlayerTournamentResult),
    'credit' : IDL.Nat,
    'stats' : TournamentStats,
    'bestReturn' : IDL.Nat,
    'allowance' : IDL.Nat,
    'faucetRemaining' : IDL.Nat,
    'top10Entry' : IDL.Nat,
    'pendingPayout' : IDL.Nat,
    'paused' : IDL.Bool,
    'endsAt' : IDL.Int,
  });
  const PickResult = IDL.Record({
    'end' : IDL.Opt(EndResult),
    'collapsed' : IDL.Bool,
    'pool' : IDL.Nat,
    'diamond' : DiamondResult,
    'credit' : IDL.Nat,
    'picks' : IDL.Nat,
    'excavation' : IDL.Opt(ExcavationView),
  });
  const Result_2 = IDL.Variant({ 'ok' : PickResult, 'err' : IDL.Text });
  const TopPrize = IDL.Record({
    'player' : IDL.Principal,
    'rank' : IDL.Nat,
    'tournament' : IDL.Nat,
    'volume' : IDL.Nat,
    'prize' : IDL.Nat,
  });
  const PlayerRow = IDL.Record({
    'staked' : IDL.Nat,
    'jackpotWon' : IDL.Nat,
    'deepest' : IDL.Nat,
    'player' : IDL.Principal,
    'excavations' : IDL.Nat,
    'rank' : IDL.Nat,
    'bestPoints' : IDL.Nat,
    'prize' : IDL.Nat,
    'returned' : IDL.Nat,
  });
  const JackpotWin = IDL.Record({
    'at' : IDL.Int,
    'player' : IDL.Principal,
    'tournament' : IDL.Nat,
    'stake' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Ranking = IDL.Record({
    'top10Pool' : IDL.Nat,
    'staked' : IDL.Nat,
    'pool' : IDL.Nat,
    'tournament' : IDL.Nat,
    'lastTop10' : IDL.Vec(TopPrize),
    'players' : IDL.Vec(PlayerRow),
    'jackpots' : IDL.Vec(JackpotWin),
    'endsAt' : IDL.Int,
  });
  const Result_1 = IDL.Variant({ 'ok' : EndResult, 'err' : IDL.Text });
  const TreasurySnapshot = IDL.Record({
    'ogy_usd' : IDL.Float64,
    'date' : IDL.Text,
    'wtn_usd' : IDL.Float64,
    'icp_usd' : IDL.Float64,
    'total_usd' : IDL.Float64,
    'ogy_amount' : IDL.Float64,
    'timestamp' : IDL.Nat64,
    'icp_amount' : IDL.Float64,
    'wtn_amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_9], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'adminListRoles' : IDL.Func([], [Result_8], ['query']),
    'adminSyncBootstrap' : IDL.Func([], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'gameAdminAckAccounting' : IDL.Func([], [Result_5], []),
    'gameAdminCloseAll' : IDL.Func([], [Result_5], []),
    'gameAdminCloseTournament' : IDL.Func([], [Result_5], []),
    'gameAdminHalt' : IDL.Func([], [Result_5], []),
    'gameAdminLedgerAllowance' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [Result],
        [],
      ),
    'gameAdminLedgerBalance' : IDL.Func([IDL.Principal], [Result], []),
    'gameAdminPay' : IDL.Func([], [Result_7], []),
    'gameAdminRefreshBank' : IDL.Func([], [Result], []),
    'gameAdminReleaseBusy' : IDL.Func([IDL.Principal], [Result_5], []),
    'gameAdminResume' : IDL.Func([], [Result_5], []),
    'gameAdminSecurity' : IDL.Func([], [Result_6], ['query']),
    'gameAdminSeedPool' : IDL.Func([IDL.Nat], [Result], []),
    'gameAdminSetDuration' : IDL.Func([IDL.Nat], [Result_5], []),
    'gameAdminSetRealLedger' : IDL.Func([IDL.Principal], [Result], []),
    'gameAdminTestDeposit' : IDL.Func([IDL.Nat], [Result], []),
    'gameAdminView' : IDL.Func([], [Result_4], ['query']),
    'gameAdminWithdraw' : IDL.Func([WithdrawKind], [Result], []),
    'gameAuto' : IDL.Func([StakeOption, IDL.Nat], [Result_3], []),
    'gameBurned' : IDL.Func([], [IDL.Nat], ['query']),
    'gameConfig' : IDL.Func([], [GameConfig], ['query']),
    'gameLoadCredit' : IDL.Func([IDL.Nat], [Result], []),
    'gameMyDashboard' : IDL.Func([], [Dashboard], ['query']),
    'gamePick' : IDL.Func([IDL.Opt(StakeOption)], [Result_2], []),
    'gameRanking' : IDL.Func([], [Ranking], ['query']),
    'gameRequestTestTokens' : IDL.Func([IDL.Nat], [Result], []),
    'gameSave' : IDL.Func([], [Result_1], []),
    'gameTestApprove' : IDL.Func([IDL.Nat], [Result], []),
    'gameTournaments' : IDL.Func([], [IDL.Vec(TournamentSummary)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTreasuryHistory' : IDL.Func([], [IDL.Vec(TreasurySnapshot)], ['query']),
    'hasSnapshot' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveTreasurySnapshot' : IDL.Func([TreasurySnapshot], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
