/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AdminView {
    durationDays: bigint;
    staked: bigint;
    stakes: Array<bigint>;
    top10: bigint;
    smallBalances: bigint;
    toCollect: bigint;
    bankAccount?: Principal;
    bank: bigint;
    fund: bigint;
    owed: bigint;
    pool: bigint;
    tournament: bigint;
    reserve: bigint;
    selfId?: Principal;
    cycles: bigint;
    lastClose?: TournamentSummary;
    withdrawable: bigint;
    smallPlayers: bigint;
    bankAllowance: bigint;
    burned: bigint;
    heldJackpots: bigint;
    toCollectPlayers: bigint;
    realLedger: boolean;
    payouts: Array<Payout>;
    paused: boolean;
    unpaidPayouts: bigint;
    endsAt: bigint;
}
export interface AutoResult {
    end: EndResult;
    pool: bigint;
    steps: Array<AutoStep>;
}
export interface AutoStep {
    collapsed: boolean;
    pick: bigint;
    diamond: DiamondResult;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Dashboard {
    net: bigint;
    top10Pool: bigint;
    top10Rank: bigint;
    stakes: Array<bigint>;
    top10Prize: bigint;
    balance: bigint;
    open?: ExcavationView;
    pool: bigint;
    tournament: bigint;
    history: Array<PastResult>;
    credit: bigint;
    stats: TournamentStats;
    bestReturn: bigint;
    allowance: bigint;
    top10Entry: bigint;
    pendingPayout: bigint;
    paused: boolean;
    endsAt: bigint;
}
export interface DiamondResult {
    won: bigint;
    stage: bigint;
}
export interface EndResult {
    won: bigint;
    jackpotWon: bigint;
    balance: bigint;
    kind: EndKind;
    lost: bigint;
    credit: bigint;
    stake: bigint;
    gross: bigint;
    picks: bigint;
    points: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ExcavationView {
    jackpotWon: bigint;
    runPoints: bigint;
    collapseGross: bigint;
    diamonds: bigint;
    nextGross: bigint;
    held: bigint;
    canSave: boolean;
    stake: bigint;
    runGross: bigint;
    picks: bigint;
    safePctX100: bigint;
}
export interface FaucetConfig {
    presets: Array<bigint>;
    usedE8s: bigint;
    enabled: boolean;
    capE8s: bigint;
}
export interface GameConfig {
    mines: bigint;
    loadMax: bigint;
    loadMin: bigint;
    top10Bps: bigint;
    ledgerId: string;
    top10Weights: Array<bigint>;
    diamond2PerGoldao: bigint;
    stakeCapE8s: bigint;
    feeE8s: bigint;
    diamond1Bps: bigint;
    cells: bigint;
    pointsTable: Array<bigint>;
    miniBps: bigint;
    creditCapE8s: bigint;
    maxPicks: bigint;
    diamond3Odds: bigint;
    top10MinVolumeE8s: bigint;
    poolSeedMaxE8s: bigint;
    poolSeedE8s: bigint;
    payoutBps: bigint;
    safePicks: bigint;
    minPayoutE8s: bigint;
    stakeMinE8s: bigint;
    realLedger: boolean;
}
export interface GameSummary {
    top10Pool: bigint;
    staked: bigint;
    totalPlayers: bigint;
    pool: bigint;
    tournament: bigint;
    paused: boolean;
    endsAt: bigint;
}
export interface JackpotWin {
    at: bigint;
    player: Principal;
    tournament: bigint;
    stake: bigint;
    amount: bigint;
}
export interface PastResult {
    net: bigint;
    staked: bigint;
    jackpotWon: bigint;
    top10Prize: bigint;
    excavations: bigint;
    tournament: bigint;
    credit: bigint;
    returned: bigint;
    payout: bigint;
}
export interface Payout {
    id: bigint;
    to: Principal;
    paid: boolean;
    txId?: bigint;
    tournament: bigint;
    uncertain: boolean;
    stamp: bigint;
    amount: bigint;
    paidAt: bigint;
}
export interface PickResult {
    end?: EndResult;
    collapsed: boolean;
    pool: bigint;
    diamond: DiamondResult;
    credit: bigint;
    picks: bigint;
    excavation?: ExcavationView;
}
export interface PlayerRow {
    net: bigint;
    pos: bigint;
    staked: bigint;
    jackpotWon: bigint;
    player: Principal;
    excavations: bigint;
    rank: bigint;
    bestReturn: bigint;
    prize: bigint;
    returned: bigint;
}
export interface RankingPage {
    totalPlayers: bigint;
    mine?: PlayerRow;
    page: bigint;
    rows: Array<PlayerRow>;
    sort: RankingSort;
    pageSize: bigint;
    lastTop10: Array<TopPrize>;
    jackpots: Array<JackpotWin>;
}
export type Result = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: EndResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: {
        paid: bigint;
        remaining: bigint;
        failed: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export type Result_11 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result_12 = {
    __kind__: "ok";
    ok: Array<[Principal, UserRole]>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_13 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_2 = {
    __kind__: "ok";
    ok: PickResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: AutoResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: AdminView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_5 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_6 = {
    __kind__: "ok";
    ok: SecurityLogView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_7 = {
    __kind__: "ok";
    ok: SecurityView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: Array<Payout>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: bigint | null;
} | {
    __kind__: "err";
    err: string;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface SecurityDay {
    day: bigint;
    events: bigint;
    attention: bigint;
}
export interface SecurityEvent {
    at: bigint;
    title: string;
    code: string;
    count: bigint;
    lastAt: bigint;
    description: string;
    level: SecurityLevel;
}
export interface SecurityLogView {
    day: bigint;
    days: Array<SecurityDay>;
    events: Array<SecurityEvent>;
}
export interface SecurityView {
    haltCode: bigint;
    ledgerFails: bigint;
    haltedAt: bigint;
    accountingOk: boolean;
    halted: boolean;
    saturations: bigint;
}
export interface TopPrize {
    player: Principal;
    rank: bigint;
    tournament: bigint;
    volume: bigint;
    prize: bigint;
}
export interface TournamentStats {
    staked: bigint;
    minis: bigint;
    jackpotWon: bigint;
    deepest: bigint;
    excavations: bigint;
    collapses: bigint;
    miniWon: bigint;
    returned: bigint;
    jackpots: bigint;
}
export interface TournamentSummary {
    staked: bigint;
    minis: bigint;
    miniPaid: bigint;
    excavations: bigint;
    jackpotPaid: bigint;
    tournament: bigint;
    closedAt: bigint;
    players: bigint;
    forfeited: bigint;
    payoutTotal: bigint;
    returned: bigint;
    jackpots: bigint;
}
export interface TreasurySnapshot {
    ogy_usd: number;
    date: string;
    wtn_usd: number;
    icp_usd: number;
    total_usd: number;
    ogy_amount: number;
    timestamp: bigint;
    icp_amount: number;
    wtn_amount: number;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum EndKind {
    maxed = "maxed",
    collapsed = "collapsed",
    saved = "saved"
}
export enum RankingSort {
    net = "net",
    jackpot = "jackpot",
    volume = "volume",
    bestPrize = "bestPrize"
}
export enum SecurityLevel {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum StakeOption {
    max = "max",
    mid = "mid",
    min = "min"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawKind {
    all = "all",
    available = "available"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_13>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    adminListRoles(): Promise<Result_12>;
    adminSyncBootstrap(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result__1>;
    gameAdminAckAccounting(): Promise<Result_5>;
    gameAdminChangeLedger(): Promise<Result>;
    gameAdminCheckPay(): Promise<Result_5>;
    gameAdminCheckWithdraw(kind: WithdrawKind): Promise<Result_5>;
    gameAdminCloseAll(): Promise<Result_5>;
    gameAdminCloseTournament(): Promise<Result_5>;
    gameAdminEnsureConnected(): Promise<Result_11>;
    gameAdminHalt(): Promise<Result_5>;
    gameAdminLedgerAllowance(who: Principal, spender: Principal): Promise<Result>;
    gameAdminLedgerBalance(who: Principal): Promise<Result>;
    gameAdminMarkPaid(id: bigint, txId: bigint): Promise<Result_5>;
    gameAdminPay(max: bigint): Promise<Result_10>;
    gameAdminPayOne(id: bigint, renew: boolean): Promise<Result_9>;
    gameAdminPayouts(tournament: bigint): Promise<Result_8>;
    gameAdminRefreshBank(): Promise<Result>;
    gameAdminReleaseBusy(player: Principal): Promise<Result_5>;
    gameAdminResume(): Promise<Result_5>;
    gameAdminSecurity(): Promise<Result_7>;
    gameAdminSecurityLog(day: bigint): Promise<Result_6>;
    gameAdminSeedPool(goldao: bigint): Promise<Result>;
    gameAdminSetDuration(days: bigint): Promise<Result_5>;
    gameAdminView(): Promise<Result_4>;
    gameAdminWithdraw(kind: WithdrawKind): Promise<Result>;
    gameAuto(stake: StakeOption, stopAt: bigint, expectedStake: bigint): Promise<Result_3>;
    gameBurned(): Promise<bigint>;
    gameConfig(): Promise<GameConfig>;
    gameLoadCredit(goldao: bigint): Promise<Result>;
    gameMyDashboard(): Promise<Dashboard>;
    gamePick(stake: StakeOption | null, expectedStake: bigint, expectedPicks: bigint): Promise<Result_2>;
    gameRankingPage(sort: RankingSort, page: bigint): Promise<RankingPage>;
    gameSave(): Promise<Result_1>;
    gameSummary(): Promise<GameSummary>;
    gameTournaments(): Promise<Array<TournamentSummary>>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Full history sorted by date ascending.
     */
    getTreasuryHistory(): Promise<Array<TreasurySnapshot>>;
    /**
     * / Check if a snapshot for the given date exists (cheap query).
     */
    hasSnapshot(date: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Save a daily snapshot. Write-once per day, only for today's date (UTC), validated in the lib.
     */
    saveTreasurySnapshot(snapshot: TreasurySnapshot): Promise<boolean>;
    schema(): Promise<string>;
    testFaucetClaim(goldao: bigint): Promise<Result>;
    testFaucetConfig(): Promise<FaucetConfig>;
    whoAmI(): Promise<string>;
}
import type { AdminView as _AdminView, AutoResult as _AutoResult, AutoStep as _AutoStep, Cell as _Cell, Dashboard as _Dashboard, DiamondResult as _DiamondResult, EndKind as _EndKind, EndResult as _EndResult, Error as _Error, ExcavationView as _ExcavationView, JackpotWin as _JackpotWin, PastResult as _PastResult, Payout as _Payout, PickResult as _PickResult, PlayerRow as _PlayerRow, RankingPage as _RankingPage, RankingSort as _RankingSort, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_13 as _Result_13, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, Result__1 as _Result__1, SecurityDay as _SecurityDay, SecurityEvent as _SecurityEvent, SecurityLevel as _SecurityLevel, SecurityLogView as _SecurityLogView, SecurityView as _SecurityView, StakeOption as _StakeOption, TopPrize as _TopPrize, TournamentStats as _TournamentStats, TournamentSummary as _TournamentSummary, UserRole as _UserRole, Value as _Value, WithdrawKind as _WithdrawKind } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_13> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_13_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_13_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async adminListRoles(): Promise<Result_12> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListRoles();
                return from_candid_Result_12_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListRoles();
            return from_candid_Result_12_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSyncBootstrap(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSyncBootstrap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSyncBootstrap();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminAckAccounting(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminAckAccounting();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminAckAccounting();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminChangeLedger(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminChangeLedger();
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminChangeLedger();
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCheckPay(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCheckPay();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCheckPay();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCheckWithdraw(arg0: WithdrawKind): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCheckWithdraw(to_candid_WithdrawKind_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCheckWithdraw(to_candid_WithdrawKind_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCloseAll(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCloseAll();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCloseAll();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCloseTournament(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCloseTournament();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCloseTournament();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminEnsureConnected(): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminEnsureConnected();
                return from_candid_Result_11_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminEnsureConnected();
            return from_candid_Result_11_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminHalt(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminHalt();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminHalt();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminLedgerAllowance(arg0: Principal, arg1: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminLedgerAllowance(arg0, arg1);
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminLedgerAllowance(arg0, arg1);
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminLedgerBalance(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminLedgerBalance(arg0);
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminLedgerBalance(arg0);
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminMarkPaid(arg0: bigint, arg1: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminMarkPaid(arg0, arg1);
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminMarkPaid(arg0, arg1);
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminPay(arg0: bigint): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminPay(arg0);
                return from_candid_Result_10_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminPay(arg0);
            return from_candid_Result_10_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminPayOne(arg0: bigint, arg1: boolean): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminPayOne(arg0, arg1);
                return from_candid_Result_9_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminPayOne(arg0, arg1);
            return from_candid_Result_9_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminPayouts(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminPayouts(arg0);
                return from_candid_Result_8_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminPayouts(arg0);
            return from_candid_Result_8_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminRefreshBank(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminRefreshBank();
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminRefreshBank();
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminReleaseBusy(arg0: Principal): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminReleaseBusy(arg0);
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminReleaseBusy(arg0);
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminResume(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminResume();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminResume();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSecurity(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSecurity();
                return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSecurity();
            return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSecurityLog(arg0: bigint): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSecurityLog(arg0);
                return from_candid_Result_6_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSecurityLog(arg0);
            return from_candid_Result_6_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSeedPool(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSeedPool(arg0);
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSeedPool(arg0);
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSetDuration(arg0: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSetDuration(arg0);
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSetDuration(arg0);
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminView(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminView();
                return from_candid_Result_4_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminView();
            return from_candid_Result_4_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminWithdraw(arg0: WithdrawKind): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminWithdraw(to_candid_WithdrawKind_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminWithdraw(to_candid_WithdrawKind_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAuto(arg0: StakeOption, arg1: bigint, arg2: bigint): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAuto(to_candid_StakeOption_n52(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Result_3_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAuto(to_candid_StakeOption_n52(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Result_3_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameBurned(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.gameBurned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameBurned();
            return result;
        }
    }
    async gameConfig(): Promise<GameConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.gameConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameConfig();
            return result;
        }
    }
    async gameLoadCredit(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameLoadCredit(arg0);
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameLoadCredit(arg0);
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameMyDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.gameMyDashboard();
                return from_candid_Dashboard_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameMyDashboard();
            return from_candid_Dashboard_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async gamePick(arg0: StakeOption | null, arg1: bigint, arg2: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.gamePick(to_candid_opt_n63(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Result_2_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gamePick(to_candid_opt_n63(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Result_2_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameRankingPage(arg0: RankingSort, arg1: bigint): Promise<RankingPage> {
        if (this.processError) {
            try {
                const result = await this.actor.gameRankingPage(to_candid_RankingSort_n69(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_RankingPage_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameRankingPage(to_candid_RankingSort_n69(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_RankingPage_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameSave(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.gameSave();
                return from_candid_Result_1_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameSave();
            return from_candid_Result_1_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameSummary(): Promise<GameSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.gameSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameSummary();
            return result;
        }
    }
    async gameTournaments(): Promise<Array<TournamentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.gameTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameTournaments();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreasuryHistory(): Promise<Array<TreasurySnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryHistory();
            return result;
        }
    }
    async hasSnapshot(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSnapshot(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveTreasurySnapshot(arg0: TreasurySnapshot): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTreasurySnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTreasurySnapshot(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async testFaucetClaim(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.testFaucetClaim(arg0);
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testFaucetClaim(arg0);
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async testFaucetConfig(): Promise<FaucetConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.testFaucetConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testFaucetConfig();
            return result;
        }
    }
    async whoAmI(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.whoAmI();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoAmI();
            return result;
        }
    }
}
function from_candid_AdminView_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminView): AdminView {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_AutoResult_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutoResult): AutoResult {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_EndKind_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndKind): EndKind {
    return "maxed" in value ? EndKind.maxed : "collapsed" in value ? EndKind.collapsed : "saved" in value ? EndKind.saved : value;
}
function from_candid_EndResult_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndResult): EndResult {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Payout_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payout): Payout {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PickResult_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickResult): PickResult {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_RankingPage_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankingPage): RankingPage {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_RankingSort_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankingSort): RankingSort {
    return "net" in value ? RankingSort.net : "jackpot" in value ? RankingSort.jackpot : "volume" in value ? RankingSort.volume : "bestPrize" in value ? RankingSort.bestPrize : value;
}
function from_candid_Result_10_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_12_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_12): Result_12 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_13_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_13): Result_13 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SecurityEvent_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecurityEvent): SecurityEvent {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_SecurityLevel_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecurityLevel): SecurityLevel {
    return "warning" in value ? SecurityLevel.warning : "info" in value ? SecurityLevel.info : "critical" in value ? SecurityLevel.critical : value;
}
function from_candid_SecurityLogView_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecurityLogView): SecurityLogView {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentSummary]): TournamentSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExcavationView]): ExcavationView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EndResult]): EndResult | null {
    return value.length === 0 ? null : from_candid_EndResult_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerRow]): PlayerRow | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n13(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n17(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: Principal;
    paid: boolean;
    txId: [] | [bigint];
    tournament: bigint;
    uncertain: boolean;
    stamp: bigint;
    amount: bigint;
    paidAt: bigint;
}): {
    id: bigint;
    to: Principal;
    paid: boolean;
    txId?: bigint;
    tournament: bigint;
    uncertain: boolean;
    stamp: bigint;
    amount: bigint;
    paidAt: bigint;
} {
    return {
        id: value.id,
        to: value.to,
        paid: value.paid,
        txId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.txId)),
        tournament: value.tournament,
        uncertain: value.uncertain,
        stamp: value.stamp,
        amount: value.amount,
        paidAt: value.paidAt
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: bigint;
    days: Array<_SecurityDay>;
    events: Array<_SecurityEvent>;
}): {
    day: bigint;
    days: Array<SecurityDay>;
    events: Array<SecurityEvent>;
} {
    return {
        day: value.day,
        days: value.days,
        events: from_candid_vec_n42(_uploadFile, _downloadFile, value.events)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    at: bigint;
    title: string;
    code: string;
    count: bigint;
    lastAt: bigint;
    description: string;
    level: _SecurityLevel;
}): {
    at: bigint;
    title: string;
    code: string;
    count: bigint;
    lastAt: bigint;
    description: string;
    level: SecurityLevel;
} {
    return {
        at: value.at,
        title: value.title,
        code: value.code,
        count: value.count,
        lastAt: value.lastAt,
        description: value.description,
        level: from_candid_SecurityLevel_n45(_uploadFile, _downloadFile, value.level)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    staked: bigint;
    stakes: Array<bigint>;
    top10: bigint;
    smallBalances: bigint;
    toCollect: bigint;
    bankAccount: [] | [Principal];
    bank: bigint;
    fund: bigint;
    owed: bigint;
    pool: bigint;
    tournament: bigint;
    reserve: bigint;
    selfId: [] | [Principal];
    cycles: bigint;
    lastClose: [] | [_TournamentSummary];
    withdrawable: bigint;
    smallPlayers: bigint;
    bankAllowance: bigint;
    burned: bigint;
    heldJackpots: bigint;
    toCollectPlayers: bigint;
    realLedger: boolean;
    payouts: Array<_Payout>;
    paused: boolean;
    unpaidPayouts: bigint;
    endsAt: bigint;
}): {
    durationDays: bigint;
    staked: bigint;
    stakes: Array<bigint>;
    top10: bigint;
    smallBalances: bigint;
    toCollect: bigint;
    bankAccount?: Principal;
    bank: bigint;
    fund: bigint;
    owed: bigint;
    pool: bigint;
    tournament: bigint;
    reserve: bigint;
    selfId?: Principal;
    cycles: bigint;
    lastClose?: TournamentSummary;
    withdrawable: bigint;
    smallPlayers: bigint;
    bankAllowance: bigint;
    burned: bigint;
    heldJackpots: bigint;
    toCollectPlayers: bigint;
    realLedger: boolean;
    payouts: Array<Payout>;
    paused: boolean;
    unpaidPayouts: bigint;
    endsAt: bigint;
} {
    return {
        durationDays: value.durationDays,
        staked: value.staked,
        stakes: value.stakes,
        top10: value.top10,
        smallBalances: value.smallBalances,
        toCollect: value.toCollect,
        bankAccount: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.bankAccount)),
        bank: value.bank,
        fund: value.fund,
        owed: value.owed,
        pool: value.pool,
        tournament: value.tournament,
        reserve: value.reserve,
        selfId: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.selfId)),
        cycles: value.cycles,
        lastClose: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.lastClose)),
        withdrawable: value.withdrawable,
        smallPlayers: value.smallPlayers,
        bankAllowance: value.bankAllowance,
        burned: value.burned,
        heldJackpots: value.heldJackpots,
        toCollectPlayers: value.toCollectPlayers,
        realLedger: value.realLedger,
        payouts: from_candid_vec_n33(_uploadFile, _downloadFile, value.payouts),
        paused: value.paused,
        unpaidPayouts: value.unpaidPayouts,
        endsAt: value.endsAt
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end: _EndResult;
    pool: bigint;
    steps: Array<_AutoStep>;
}): {
    end: EndResult;
    pool: bigint;
    steps: Array<AutoStep>;
} {
    return {
        end: from_candid_EndResult_n57(_uploadFile, _downloadFile, value.end),
        pool: value.pool,
        steps: value.steps
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: bigint;
    jackpotWon: bigint;
    balance: bigint;
    kind: _EndKind;
    lost: bigint;
    credit: bigint;
    stake: bigint;
    gross: bigint;
    picks: bigint;
    points: bigint;
}): {
    won: bigint;
    jackpotWon: bigint;
    balance: bigint;
    kind: EndKind;
    lost: bigint;
    credit: bigint;
    stake: bigint;
    gross: bigint;
    picks: bigint;
    points: bigint;
} {
    return {
        won: value.won,
        jackpotWon: value.jackpotWon,
        balance: value.balance,
        kind: from_candid_EndKind_n59(_uploadFile, _downloadFile, value.kind),
        lost: value.lost,
        credit: value.credit,
        stake: value.stake,
        gross: value.gross,
        picks: value.picks,
        points: value.points
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    net: bigint;
    top10Pool: bigint;
    top10Rank: bigint;
    stakes: Array<bigint>;
    top10Prize: bigint;
    balance: bigint;
    open: [] | [_ExcavationView];
    pool: bigint;
    tournament: bigint;
    history: Array<_PastResult>;
    credit: bigint;
    stats: _TournamentStats;
    bestReturn: bigint;
    allowance: bigint;
    top10Entry: bigint;
    pendingPayout: bigint;
    paused: boolean;
    endsAt: bigint;
}): {
    net: bigint;
    top10Pool: bigint;
    top10Rank: bigint;
    stakes: Array<bigint>;
    top10Prize: bigint;
    balance: bigint;
    open?: ExcavationView;
    pool: bigint;
    tournament: bigint;
    history: Array<PastResult>;
    credit: bigint;
    stats: TournamentStats;
    bestReturn: bigint;
    allowance: bigint;
    top10Entry: bigint;
    pendingPayout: bigint;
    paused: boolean;
    endsAt: bigint;
} {
    return {
        net: value.net,
        top10Pool: value.top10Pool,
        top10Rank: value.top10Rank,
        stakes: value.stakes,
        top10Prize: value.top10Prize,
        balance: value.balance,
        open: record_opt_to_undefined(from_candid_opt_n62(_uploadFile, _downloadFile, value.open)),
        pool: value.pool,
        tournament: value.tournament,
        history: value.history,
        credit: value.credit,
        stats: value.stats,
        bestReturn: value.bestReturn,
        allowance: value.allowance,
        top10Entry: value.top10Entry,
        pendingPayout: value.pendingPayout,
        paused: value.paused,
        endsAt: value.endsAt
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end: [] | [_EndResult];
    collapsed: boolean;
    pool: bigint;
    diamond: _DiamondResult;
    credit: bigint;
    picks: bigint;
    excavation: [] | [_ExcavationView];
}): {
    end?: EndResult;
    collapsed: boolean;
    pool: bigint;
    diamond: DiamondResult;
    credit: bigint;
    picks: bigint;
    excavation?: ExcavationView;
} {
    return {
        end: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.end)),
        collapsed: value.collapsed,
        pool: value.pool,
        diamond: value.diamond,
        credit: value.credit,
        picks: value.picks,
        excavation: record_opt_to_undefined(from_candid_opt_n62(_uploadFile, _downloadFile, value.excavation))
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPlayers: bigint;
    mine: [] | [_PlayerRow];
    page: bigint;
    rows: Array<_PlayerRow>;
    sort: _RankingSort;
    pageSize: bigint;
    lastTop10: Array<_TopPrize>;
    jackpots: Array<_JackpotWin>;
}): {
    totalPlayers: bigint;
    mine?: PlayerRow;
    page: bigint;
    rows: Array<PlayerRow>;
    sort: RankingSort;
    pageSize: bigint;
    lastTop10: Array<TopPrize>;
    jackpots: Array<JackpotWin>;
} {
    return {
        totalPlayers: value.totalPlayers,
        mine: record_opt_to_undefined(from_candid_opt_n72(_uploadFile, _downloadFile, value.mine)),
        page: value.page,
        rows: value.rows,
        sort: from_candid_RankingSort_n73(_uploadFile, _downloadFile, value.sort),
        pageSize: value.pageSize,
        lastTop10: value.lastTop10,
        jackpots: value.jackpots
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserRole]): [Principal, UserRole] {
    return [
        value[0],
        from_candid_UserRole_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        paid: bigint;
        remaining: bigint;
        failed: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        paid: bigint;
        remaining: bigint;
        failed: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [bigint];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Payout>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Payout>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SecurityView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SecurityView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SecurityLogView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SecurityLogView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SecurityLogView_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AdminView_n48(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AutoResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AutoResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AutoResult_n55(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[Principal, _UserRole]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[Principal, UserRole]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PickResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PickResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PickResult_n66(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _EndResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: EndResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_EndResult_n57(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payout>): Array<Payout> {
    return value.map((x)=>from_candid_Payout_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SecurityEvent>): Array<SecurityEvent> {
    return value.map((x)=>from_candid_SecurityEvent_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserRole]>): Array<[Principal, UserRole]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_RankingSort_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RankingSort): _RankingSort {
    return value == RankingSort.net ? {
        net: null
    } : value == RankingSort.jackpot ? {
        jackpot: null
    } : value == RankingSort.volume ? {
        volume: null
    } : value == RankingSort.bestPrize ? {
        bestPrize: null
    } : value;
}
function to_candid_StakeOption_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StakeOption): _StakeOption {
    return value == StakeOption.max ? {
        max: null
    } : value == StakeOption.mid ? {
        mid: null
    } : value == StakeOption.min ? {
        min: null
    } : value;
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_WithdrawKind_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawKind): _WithdrawKind {
    return value == WithdrawKind.all ? {
        all: null
    } : value == WithdrawKind.available ? {
        available: null
    } : value;
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StakeOption | null): [] | [_StakeOption] {
    return value === null ? candid_none() : candid_some(to_candid_StakeOption_n52(_uploadFile, _downloadFile, value));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
