/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AdminView {
    durationDays: bigint;
    staked: bigint;
    stakes: Array<bigint>;
    top10: bigint;
    smallBalances: bigint;
    toCollect: bigint;
    bankAccount?: Principal;
    bank: bigint;
    fund: bigint;
    owed: bigint;
    pool: bigint;
    tournament: bigint;
    reserve: bigint;
    selfId?: Principal;
    cycles: bigint;
    lastClose?: TournamentSummary;
    withdrawable: bigint;
    smallPlayers: bigint;
    bankAllowance: bigint;
    burned: bigint;
    heldJackpots: bigint;
    toCollectPlayers: bigint;
    realLedger: boolean;
    payouts: Array<Payout>;
    paused: boolean;
    unpaidPayouts: bigint;
    endsAt: bigint;
}
export interface AutoResult {
    end: EndResult;
    pool: bigint;
    steps: Array<AutoStep>;
}
export interface AutoStep {
    collapsed: boolean;
    pick: bigint;
    diamond: DiamondResult;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Dashboard {
    top10Pool: bigint;
    top10Rank: bigint;
    stakes: Array<bigint>;
    top10Prize: bigint;
    balance: bigint;
    open?: ExcavationView;
    pool: bigint;
    tournament: bigint;
    history: Array<PlayerTournamentResult>;
    credit: bigint;
    stats: TournamentStats;
    bestReturn: bigint;
    allowance: bigint;
    faucetRemaining: bigint;
    top10Entry: bigint;
    pendingPayout: bigint;
    paused: boolean;
    endsAt: bigint;
}
export interface DiamondResult {
    won: bigint;
    stage: bigint;
}
export interface EndResult {
    won: bigint;
    jackpotWon: bigint;
    balance: bigint;
    kind: EndKind;
    lost: bigint;
    credit: bigint;
    stake: bigint;
    gross: bigint;
    picks: bigint;
    points: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ExcavationView {
    jackpotWon: bigint;
    runPoints: bigint;
    collapseGross: bigint;
    diamonds: bigint;
    nextGross: bigint;
    held: bigint;
    canSave: boolean;
    stake: bigint;
    runGross: bigint;
    picks: bigint;
    safePctX100: bigint;
}
export type GResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_1 = {
    __kind__: "ok";
    ok: EndResult;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_2 = {
    __kind__: "ok";
    ok: PickResult;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_3 = {
    __kind__: "ok";
    ok: AutoResult;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_4 = {
    __kind__: "ok";
    ok: AdminView;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_5 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_6 = {
    __kind__: "ok";
    ok: SecurityView;
} | {
    __kind__: "err";
    err: string;
};
export type GResult_7 = {
    __kind__: "ok";
    ok: {
        paid: bigint;
        remaining: bigint;
        failed: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export type GResult_8 = {
    __kind__: "ok";
    ok: Array<[Principal, UserRole]>;
} | {
    __kind__: "err";
    err: string;
};
export interface GameConfig {
    mines: bigint;
    loadMax: bigint;
    loadMin: bigint;
    top10Bps: bigint;
    ledgerId: string;
    top10Weights: Array<bigint>;
    stakeCapE8s: bigint;
    feeE8s: bigint;
    diamond1Bps: bigint;
    diamond2Bps: bigint;
    cells: bigint;
    pointsTable: Array<bigint>;
    creditCapE8s: bigint;
    maxPicks: bigint;
    top10MinVolumeE8s: bigint;
    payoutBps: bigint;
    safePicks: bigint;
    minPayoutE8s: bigint;
    stakeMinE8s: bigint;
    faucetCapE8s: bigint;
    realLedger: boolean;
    diamond3PerGoldao: bigint;
}
export interface JackpotWin {
    at: bigint;
    player: Principal;
    tournament: bigint;
    stake: bigint;
    amount: bigint;
}
export interface Payout {
    id: bigint;
    to: Principal;
    paid: boolean;
    tournament: bigint;
    stamp: bigint;
    amount: bigint;
}
export interface PickResult {
    end?: EndResult;
    collapsed: boolean;
    pool: bigint;
    diamond: DiamondResult;
    credit: bigint;
    picks: bigint;
    excavation?: ExcavationView;
}
export interface PlayerRow {
    staked: bigint;
    jackpotWon: bigint;
    deepest: bigint;
    player: Principal;
    excavations: bigint;
    rank: bigint;
    bestPoints: bigint;
    prize: bigint;
    returned: bigint;
}
export interface PlayerTournamentResult {
    tournament: bigint;
    credit: bigint;
    stats: TournamentStats;
    payout: bigint;
}
export interface Ranking {
    top10Pool: bigint;
    staked: bigint;
    pool: bigint;
    tournament: bigint;
    lastTop10: Array<TopPrize>;
    players: Array<PlayerRow>;
    jackpots: Array<JackpotWin>;
    endsAt: bigint;
}
export type Result_7 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface SecurityView {
    haltCode: bigint;
    ledgerFails: bigint;
    haltedAt: bigint;
    accountingOk: boolean;
    halted: boolean;
    saturations: bigint;
}
export interface TopPrize {
    player: Principal;
    rank: bigint;
    tournament: bigint;
    volume: bigint;
    prize: bigint;
}
export interface TournamentStats {
    staked: bigint;
    jackpotWon: bigint;
    deepest: bigint;
    excavations: bigint;
    collapses: bigint;
    bestPoints: bigint;
    charged: bigint;
    returned: bigint;
    jackpots: bigint;
}
export interface TournamentSummary {
    staked: bigint;
    excavations: bigint;
    jackpotPaid: bigint;
    tournament: bigint;
    closedAt: bigint;
    players: bigint;
    forfeited: bigint;
    payoutTotal: bigint;
    returned: bigint;
    jackpots: bigint;
}
export interface TreasurySnapshot {
    ogy_usd: number;
    date: string;
    wtn_usd: number;
    icp_usd: number;
    total_usd: number;
    ogy_amount: number;
    timestamp: bigint;
    icp_amount: number;
    wtn_amount: number;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum EndKind {
    maxed = "maxed",
    collapsed = "collapsed",
    saved = "saved"
}
export enum StakeOption {
    max = "max",
    mid = "mid",
    min = "min"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawKind {
    all = "all",
    available = "available"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_7>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    adminListRoles(): Promise<GResult_8>;
    adminSyncBootstrap(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result__1>;
    gameAdminAckAccounting(): Promise<GResult_5>;
    gameAdminCloseAll(): Promise<GResult_5>;
    gameAdminCloseTournament(): Promise<GResult_5>;
    gameAdminHalt(): Promise<GResult_5>;
    gameAdminLedgerAllowance(who: Principal, spender: Principal): Promise<GResult>;
    gameAdminLedgerBalance(who: Principal): Promise<GResult>;
    gameAdminPay(): Promise<GResult_7>;
    gameAdminRefreshBank(): Promise<GResult>;
    gameAdminReleaseBusy(player: Principal): Promise<GResult_5>;
    gameAdminResume(): Promise<GResult_5>;
    gameAdminSecurity(): Promise<GResult_6>;
    gameAdminSeedPool(): Promise<GResult>;
    gameAdminSetDuration(days: bigint): Promise<GResult_5>;
    gameAdminSetRealLedger(selfId: Principal): Promise<GResult>;
    gameAdminTestDeposit(goldao: bigint): Promise<GResult>;
    gameAdminView(): Promise<GResult_4>;
    gameAdminWithdraw(kind: WithdrawKind): Promise<GResult>;
    gameAuto(stake: StakeOption, stopAt: bigint): Promise<GResult_3>;
    gameBurned(): Promise<bigint>;
    gameConfig(): Promise<GameConfig>;
    gameLoadCredit(goldao: bigint): Promise<GResult>;
    gameMyDashboard(): Promise<Dashboard>;
    gamePick(stake: StakeOption | null): Promise<GResult_2>;
    gameRanking(): Promise<Ranking>;
    gameRequestTestTokens(goldao: bigint): Promise<GResult>;
    gameSave(): Promise<GResult_1>;
    gameTestApprove(goldao: bigint): Promise<GResult>;
    gameTournaments(): Promise<Array<TournamentSummary>>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Full history sorted by date ascending.
     */
    getTreasuryHistory(): Promise<Array<TreasurySnapshot>>;
    /**
     * / Check if a snapshot for the given date exists (cheap query).
     */
    hasSnapshot(date: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Save a daily snapshot. Write-once per day — rejects if date exists.
     */
    saveTreasurySnapshot(snapshot: TreasurySnapshot): Promise<boolean>;
    schema(): Promise<string>;
    whoAmI(): Promise<string>;
}
import type { AdminView as _AdminView, AutoResult as _AutoResult, AutoStep as _AutoStep, Cell as _Cell, Dashboard as _Dashboard, DiamondResult as _DiamondResult, EndKind as _EndKind, EndResult as _EndResult, Error as _Error, ExcavationView as _ExcavationView, GResult as _GResult, GResult_1 as _GResult_1, GResult_2 as _GResult_2, GResult_3 as _GResult_3, GResult_4 as _GResult_4, GResult_5 as _GResult_5, GResult_6 as _GResult_6, GResult_7 as _GResult_7, GResult_8 as _GResult_8, Payout as _Payout, PickResult as _PickResult, PlayerTournamentResult as _PlayerTournamentResult, Result_7 as _Result_7, Result__1 as _Result__1, SecurityView as _SecurityView, StakeOption as _StakeOption, TournamentStats as _TournamentStats, TournamentSummary as _TournamentSummary, UserRole as _UserRole, Value as _Value, WithdrawKind as _WithdrawKind } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async adminListRoles(): Promise<GResult_8> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListRoles();
                return from_candid_GResult_8_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListRoles();
            return from_candid_GResult_8_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSyncBootstrap(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSyncBootstrap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSyncBootstrap();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminAckAccounting(): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminAckAccounting();
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminAckAccounting();
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCloseAll(): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCloseAll();
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCloseAll();
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCloseTournament(): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCloseTournament();
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCloseTournament();
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminHalt(): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminHalt();
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminHalt();
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminLedgerAllowance(arg0: Principal, arg1: Principal): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminLedgerAllowance(arg0, arg1);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminLedgerAllowance(arg0, arg1);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminLedgerBalance(arg0: Principal): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminLedgerBalance(arg0);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminLedgerBalance(arg0);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminPay(): Promise<GResult_7> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminPay();
                return from_candid_GResult_7_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminPay();
            return from_candid_GResult_7_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminRefreshBank(): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminRefreshBank();
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminRefreshBank();
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminReleaseBusy(arg0: Principal): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminReleaseBusy(arg0);
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminReleaseBusy(arg0);
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminResume(): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminResume();
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminResume();
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSecurity(): Promise<GResult_6> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSecurity();
                return from_candid_GResult_6_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSecurity();
            return from_candid_GResult_6_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSeedPool(): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSeedPool();
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSeedPool();
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSetDuration(arg0: bigint): Promise<GResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSetDuration(arg0);
                return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSetDuration(arg0);
            return from_candid_GResult_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminSetRealLedger(arg0: Principal): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminSetRealLedger(arg0);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminSetRealLedger(arg0);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminTestDeposit(arg0: bigint): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminTestDeposit(arg0);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminTestDeposit(arg0);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminView(): Promise<GResult_4> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminView();
                return from_candid_GResult_4_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminView();
            return from_candid_GResult_4_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminWithdraw(arg0: WithdrawKind): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminWithdraw(to_candid_WithdrawKind_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminWithdraw(to_candid_WithdrawKind_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAuto(arg0: StakeOption, arg1: bigint): Promise<GResult_3> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAuto(to_candid_StakeOption_n34(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_GResult_3_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAuto(to_candid_StakeOption_n34(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_GResult_3_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameBurned(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.gameBurned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameBurned();
            return result;
        }
    }
    async gameConfig(): Promise<GameConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.gameConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameConfig();
            return result;
        }
    }
    async gameLoadCredit(arg0: bigint): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameLoadCredit(arg0);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameLoadCredit(arg0);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameMyDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.gameMyDashboard();
                return from_candid_Dashboard_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameMyDashboard();
            return from_candid_Dashboard_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async gamePick(arg0: StakeOption | null): Promise<GResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.gamePick(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GResult_2_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gamePick(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GResult_2_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameRanking(): Promise<Ranking> {
        if (this.processError) {
            try {
                const result = await this.actor.gameRanking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameRanking();
            return result;
        }
    }
    async gameRequestTestTokens(arg0: bigint): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameRequestTestTokens(arg0);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameRequestTestTokens(arg0);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameSave(): Promise<GResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.gameSave();
                return from_candid_GResult_1_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameSave();
            return from_candid_GResult_1_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameTestApprove(arg0: bigint): Promise<GResult> {
        if (this.processError) {
            try {
                const result = await this.actor.gameTestApprove(arg0);
                return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameTestApprove(arg0);
            return from_candid_GResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameTournaments(): Promise<Array<TournamentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.gameTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameTournaments();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreasuryHistory(): Promise<Array<TreasurySnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryHistory();
            return result;
        }
    }
    async hasSnapshot(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSnapshot(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveTreasurySnapshot(arg0: TreasurySnapshot): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTreasurySnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTreasurySnapshot(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async whoAmI(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.whoAmI();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoAmI();
            return result;
        }
    }
}
function from_candid_AdminView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminView): AdminView {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_AutoResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutoResult): AutoResult {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_EndKind_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndKind): EndKind {
    return "maxed" in value ? EndKind.maxed : "collapsed" in value ? EndKind.collapsed : "saved" in value ? EndKind.saved : value;
}
function from_candid_EndResult_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndResult): EndResult {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_1_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_1): GResult_1 {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_2_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_2): GResult_2 {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_3_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_3): GResult_3 {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_4_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_4): GResult_4 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_5_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_5): GResult_5 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_6_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_6): GResult_6 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_7_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_7): GResult_7 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_8_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult_8): GResult_8 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_GResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GResult): GResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PickResult_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickResult): PickResult {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentSummary]): TournamentSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExcavationView]): ExcavationView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EndResult]): EndResult | null {
    return value.length === 0 ? null : from_candid_EndResult_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n13(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n17(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    staked: bigint;
    stakes: Array<bigint>;
    top10: bigint;
    smallBalances: bigint;
    toCollect: bigint;
    bankAccount: [] | [Principal];
    bank: bigint;
    fund: bigint;
    owed: bigint;
    pool: bigint;
    tournament: bigint;
    reserve: bigint;
    selfId: [] | [Principal];
    cycles: bigint;
    lastClose: [] | [_TournamentSummary];
    withdrawable: bigint;
    smallPlayers: bigint;
    bankAllowance: bigint;
    burned: bigint;
    heldJackpots: bigint;
    toCollectPlayers: bigint;
    realLedger: boolean;
    payouts: Array<_Payout>;
    paused: boolean;
    unpaidPayouts: bigint;
    endsAt: bigint;
}): {
    durationDays: bigint;
    staked: bigint;
    stakes: Array<bigint>;
    top10: bigint;
    smallBalances: bigint;
    toCollect: bigint;
    bankAccount?: Principal;
    bank: bigint;
    fund: bigint;
    owed: bigint;
    pool: bigint;
    tournament: bigint;
    reserve: bigint;
    selfId?: Principal;
    cycles: bigint;
    lastClose?: TournamentSummary;
    withdrawable: bigint;
    smallPlayers: bigint;
    bankAllowance: bigint;
    burned: bigint;
    heldJackpots: bigint;
    toCollectPlayers: bigint;
    realLedger: boolean;
    payouts: Array<Payout>;
    paused: boolean;
    unpaidPayouts: bigint;
    endsAt: bigint;
} {
    return {
        durationDays: value.durationDays,
        staked: value.staked,
        stakes: value.stakes,
        top10: value.top10,
        smallBalances: value.smallBalances,
        toCollect: value.toCollect,
        bankAccount: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.bankAccount)),
        bank: value.bank,
        fund: value.fund,
        owed: value.owed,
        pool: value.pool,
        tournament: value.tournament,
        reserve: value.reserve,
        selfId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.selfId)),
        cycles: value.cycles,
        lastClose: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.lastClose)),
        withdrawable: value.withdrawable,
        smallPlayers: value.smallPlayers,
        bankAllowance: value.bankAllowance,
        burned: value.burned,
        heldJackpots: value.heldJackpots,
        toCollectPlayers: value.toCollectPlayers,
        realLedger: value.realLedger,
        payouts: value.payouts,
        paused: value.paused,
        unpaidPayouts: value.unpaidPayouts,
        endsAt: value.endsAt
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end: _EndResult;
    pool: bigint;
    steps: Array<_AutoStep>;
}): {
    end: EndResult;
    pool: bigint;
    steps: Array<AutoStep>;
} {
    return {
        end: from_candid_EndResult_n39(_uploadFile, _downloadFile, value.end),
        pool: value.pool,
        steps: value.steps
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: bigint;
    jackpotWon: bigint;
    balance: bigint;
    kind: _EndKind;
    lost: bigint;
    credit: bigint;
    stake: bigint;
    gross: bigint;
    picks: bigint;
    points: bigint;
}): {
    won: bigint;
    jackpotWon: bigint;
    balance: bigint;
    kind: EndKind;
    lost: bigint;
    credit: bigint;
    stake: bigint;
    gross: bigint;
    picks: bigint;
    points: bigint;
} {
    return {
        won: value.won,
        jackpotWon: value.jackpotWon,
        balance: value.balance,
        kind: from_candid_EndKind_n41(_uploadFile, _downloadFile, value.kind),
        lost: value.lost,
        credit: value.credit,
        stake: value.stake,
        gross: value.gross,
        picks: value.picks,
        points: value.points
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    top10Pool: bigint;
    top10Rank: bigint;
    stakes: Array<bigint>;
    top10Prize: bigint;
    balance: bigint;
    open: [] | [_ExcavationView];
    pool: bigint;
    tournament: bigint;
    history: Array<_PlayerTournamentResult>;
    credit: bigint;
    stats: _TournamentStats;
    bestReturn: bigint;
    allowance: bigint;
    faucetRemaining: bigint;
    top10Entry: bigint;
    pendingPayout: bigint;
    paused: boolean;
    endsAt: bigint;
}): {
    top10Pool: bigint;
    top10Rank: bigint;
    stakes: Array<bigint>;
    top10Prize: bigint;
    balance: bigint;
    open?: ExcavationView;
    pool: bigint;
    tournament: bigint;
    history: Array<PlayerTournamentResult>;
    credit: bigint;
    stats: TournamentStats;
    bestReturn: bigint;
    allowance: bigint;
    faucetRemaining: bigint;
    top10Entry: bigint;
    pendingPayout: bigint;
    paused: boolean;
    endsAt: bigint;
} {
    return {
        top10Pool: value.top10Pool,
        top10Rank: value.top10Rank,
        stakes: value.stakes,
        top10Prize: value.top10Prize,
        balance: value.balance,
        open: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.open)),
        pool: value.pool,
        tournament: value.tournament,
        history: value.history,
        credit: value.credit,
        stats: value.stats,
        bestReturn: value.bestReturn,
        allowance: value.allowance,
        faucetRemaining: value.faucetRemaining,
        top10Entry: value.top10Entry,
        pendingPayout: value.pendingPayout,
        paused: value.paused,
        endsAt: value.endsAt
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end: [] | [_EndResult];
    collapsed: boolean;
    pool: bigint;
    diamond: _DiamondResult;
    credit: bigint;
    picks: bigint;
    excavation: [] | [_ExcavationView];
}): {
    end?: EndResult;
    collapsed: boolean;
    pool: bigint;
    diamond: DiamondResult;
    credit: bigint;
    picks: bigint;
    excavation?: ExcavationView;
} {
    return {
        end: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.end)),
        collapsed: value.collapsed,
        pool: value.pool,
        diamond: value.diamond,
        credit: value.credit,
        picks: value.picks,
        excavation: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.excavation))
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserRole]): [Principal, UserRole] {
    return [
        value[0],
        from_candid_UserRole_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        paid: bigint;
        remaining: bigint;
        failed: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        paid: bigint;
        remaining: bigint;
        failed: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SecurityView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SecurityView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AdminView_n29(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AutoResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AutoResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AutoResult_n37(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PickResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PickResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PickResult_n48(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _EndResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: EndResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_EndResult_n39(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[Principal, _UserRole]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[Principal, UserRole]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserRole]>): Array<[Principal, UserRole]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_StakeOption_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StakeOption): _StakeOption {
    return value == StakeOption.max ? {
        max: null
    } : value == StakeOption.mid ? {
        mid: null
    } : value == StakeOption.min ? {
        min: null
    } : value;
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_WithdrawKind_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawKind): _WithdrawKind {
    return value == WithdrawKind.all ? {
        all: null
    } : value == WithdrawKind.available ? {
        available: null
    } : value;
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StakeOption | null): [] | [_StakeOption] {
    return value === null ? candid_none() : candid_some(to_candid_StakeOption_n34(_uploadFile, _downloadFile, value));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
