/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AdminView {
    status: WeekStatus;
    drawCarry: bigint;
    week: bigint;
    lastClose?: WeekSummary;
    burned: bigint;
    payouts: Array<Payout>;
    treasury: bigint;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ChipView {
    id: bigint;
    diamonds: bigint;
    tier: TierIndex;
    used: bigint;
    avgX100: bigint;
    projectedX100: bigint;
    gapToNextX100?: bigint;
    points: bigint;
}
export interface Dashboard {
    status: WeekStatus;
    tiers: Array<bigint>;
    balance: bigint;
    diamonds: bigint;
    chips: Array<ChipView>;
    open?: ExcavationView;
    paid: bigint;
    week: bigint;
    history: Array<PlayerWeekResult>;
    totalDiamonds: bigint;
    stats: WeekStats;
    excavationsLeft: bigint;
    faucetRemaining: bigint;
    estimatedReceive: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ExcavationView {
    runPoints: bigint;
    diamonds: bigint;
    canSave: boolean;
    ifCollapse: bigint;
    nextPoints: bigint;
    chipId: bigint;
    picks: bigint;
    safePctX100: bigint;
}
export interface GameConfig {
    status: WeekStatus;
    mines: bigint;
    feeE8s: bigint;
    minChips: bigint;
    cells: bigint;
    pointsTable: Array<bigint>;
    week: bigint;
    minPlayers: bigint;
    treasuryBps: bigint;
    chipPriceE8s: bigint;
    tierCutsPct: Array<bigint>;
    safePicks: bigint;
    tierMultBps: Array<bigint>;
    faucetCapE8s: bigint;
    excavationsPerChip: bigint;
    drawBps: bigint;
    diamondBps: bigint;
}
export interface Payout {
    to: Principal;
    concept: PayoutConcept;
    tiers: Array<bigint>;
    amount: bigint;
}
export interface PickResult {
    collapsed: boolean;
    diamond: boolean;
    ended: boolean;
    pointsSaved: bigint;
    picks: bigint;
    excavation?: ExcavationView;
}
export interface PlayerRow {
    tiers: Array<bigint>;
    player: Principal;
    diamonds: bigint;
    chips: bigint;
    paid: bigint;
    avgX100: bigint;
    playing: boolean;
    estimatedReceive: bigint;
}
export interface PlayerWeekResult {
    tiers: Array<bigint>;
    deepest: bigint;
    diamonds: bigint;
    collapses: bigint;
    best: bigint;
    chips: bigint;
    paid: bigint;
    week: bigint;
    received: bigint;
    drawWon: boolean;
}
export interface Ranking {
    pot: bigint;
    status: WeekStatus;
    treasurePerChip: bigint;
    treasuryKeep: bigint;
    chips: bigint;
    week: bigint;
    totalDiamonds: bigint;
    players: Array<PlayerRow>;
    drawPrize: bigint;
    cutsX100: Array<bigint | null>;
}
export type Result = {
    __kind__: "ok";
    ok: ExcavationView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_2 = {
    __kind__: "ok";
    ok: PickResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: AdminView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_5 = {
    __kind__: "ok";
    ok: WeekSummary;
} | {
    __kind__: "err";
    err: string;
};
export type Result_6 = {
    __kind__: "ok";
    ok: Array<[Principal, UserRole]>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_7 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type TierIndex = bigint;
export interface TreasurySnapshot {
    ogy_usd: number;
    date: string;
    wtn_usd: number;
    icp_usd: number;
    total_usd: number;
    ogy_amount: number;
    timestamp: bigint;
    icp_amount: number;
    wtn_amount: number;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface WeekStats {
    deepest: bigint;
    playTx: bigint;
    collapses: bigint;
    best: bigint;
}
export interface WeekSummary {
    pot: bigint;
    treasurePerChip: bigint;
    treasuryKeep: bigint;
    chips: bigint;
    week: bigint;
    drawTicket: bigint;
    drawTickets: bigint;
    closedAt: bigint;
    players: bigint;
    drawPrize: bigint;
    drawWinner?: Principal;
    drawRandom: bigint;
}
export enum PayoutConcept {
    draw = "draw",
    prize = "prize"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WeekStatus {
    closed = "closed",
    open = "open",
    closing = "closing"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_7>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Lists every principal that has a role. Admin only.
     */
    adminListRoles(): Promise<Result_6>;
    /**
     * / Syncs the app-wide admin role for the hardcoded bootstrap principals (Game.BOOTSTRAP_ADMINS).
     * / Returns true only when the caller is one of them; does nothing otherwise.
     */
    adminSyncBootstrap(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result__1>;
    /**
     * / Closes the week: saves open excavations, auto-plays the remaining ones
     * / saving at 3, ranks chips, computes payouts and runs the diamond draw.
     */
    gameAdminCloseWeek(): Promise<Result_5>;
    /**
     * / Credits all payouts (simulated), archives the week and opens the next one.
     */
    gameAdminPayAndOpenNext(): Promise<Result_1>;
    /**
     * / Recovery: if a close was interrupted (status stuck in #closing), reopens the week
     * / so the admin can run the close again. Open excavations were already saved.
     */
    gameAdminRecoverClosing(): Promise<Result_4>;
    gameAdminView(): Promise<Result_3>;
    /**
     * / Buys chips: sends n x 1,000 to the treasury + 10 fee.
     */
    gameBuyChips(n: bigint): Promise<Result_1>;
    gameConfig(): Promise<GameConfig>;
    gameMyDashboard(): Promise<Dashboard>;
    /**
     * / One pick. Calls raw_rand to resolve collapse (from the 3rd pick) and diamond.
     */
    gamePick(): Promise<Result_2>;
    gameRanking(): Promise<Ranking>;
    /**
     * / Test GOLDAO: up to FAUCET_CAP per principal per week.
     */
    gameRequestTestTokens(goldao: bigint): Promise<Result_1>;
    gameSave(): Promise<Result_1>;
    gameStartExcavation(): Promise<Result>;
    gameWeeks(): Promise<Array<WeekSummary>>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Full history sorted by date ascending.
     */
    getTreasuryHistory(): Promise<Array<TreasurySnapshot>>;
    /**
     * / Check if a snapshot for the given date exists (cheap query).
     */
    hasSnapshot(date: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Save a daily snapshot. Write-once per day — rejects if date exists.
     */
    saveTreasurySnapshot(snapshot: TreasurySnapshot): Promise<boolean>;
    schema(): Promise<string>;
    /**
     * / Returns the caller's principal as text.
     */
    whoAmI(): Promise<string>;
}
import type { AdminView as _AdminView, Cell as _Cell, ChipView as _ChipView, Dashboard as _Dashboard, Error as _Error, ExcavationView as _ExcavationView, GameConfig as _GameConfig, Payout as _Payout, PayoutConcept as _PayoutConcept, PickResult as _PickResult, PlayerRow as _PlayerRow, PlayerWeekResult as _PlayerWeekResult, Ranking as _Ranking, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result__1 as _Result__1, TierIndex as _TierIndex, UserRole as _UserRole, Value as _Value, WeekStats as _WeekStats, WeekStatus as _WeekStatus, WeekSummary as _WeekSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async adminListRoles(): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListRoles();
                return from_candid_Result_6_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListRoles();
            return from_candid_Result_6_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSyncBootstrap(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSyncBootstrap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSyncBootstrap();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminCloseWeek(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminCloseWeek();
                return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminCloseWeek();
            return from_candid_Result_5_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminPayAndOpenNext(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminPayAndOpenNext();
                return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminPayAndOpenNext();
            return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminRecoverClosing(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminRecoverClosing();
                return from_candid_Result_4_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminRecoverClosing();
            return from_candid_Result_4_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameAdminView(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.gameAdminView();
                return from_candid_Result_3_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameAdminView();
            return from_candid_Result_3_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameBuyChips(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.gameBuyChips(arg0);
                return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameBuyChips(arg0);
            return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameConfig(): Promise<GameConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.gameConfig();
                return from_candid_GameConfig_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameConfig();
            return from_candid_GameConfig_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameMyDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.gameMyDashboard();
                return from_candid_Dashboard_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameMyDashboard();
            return from_candid_Dashboard_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async gamePick(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.gamePick();
                return from_candid_Result_2_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gamePick();
            return from_candid_Result_2_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameRanking(): Promise<Ranking> {
        if (this.processError) {
            try {
                const result = await this.actor.gameRanking();
                return from_candid_Ranking_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameRanking();
            return from_candid_Ranking_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameRequestTestTokens(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.gameRequestTestTokens(arg0);
                return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameRequestTestTokens(arg0);
            return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameSave(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.gameSave();
                return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameSave();
            return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameStartExcavation(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gameStartExcavation();
                return from_candid_Result_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameStartExcavation();
            return from_candid_Result_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async gameWeeks(): Promise<Array<WeekSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.gameWeeks();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gameWeeks();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreasuryHistory(): Promise<Array<TreasurySnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryHistory();
            return result;
        }
    }
    async hasSnapshot(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSnapshot(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveTreasurySnapshot(arg0: TreasurySnapshot): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTreasurySnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTreasurySnapshot(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async whoAmI(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.whoAmI();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoAmI();
            return result;
        }
    }
}
function from_candid_AdminView_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminView): AdminView {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ChipView_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChipView): ChipView {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GameConfig_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameConfig): GameConfig {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutConcept_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutConcept): PayoutConcept {
    return "draw" in value ? PayoutConcept.draw : "prize" in value ? PayoutConcept.prize : value;
}
function from_candid_Payout_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payout): Payout {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PickResult_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickResult): PickResult {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Ranking_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ranking): Ranking {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WeekStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeekStatus): WeekStatus {
    return "closed" in value ? WeekStatus.closed : "open" in value ? WeekStatus.open : "closing" in value ? WeekStatus.closing : value;
}
function from_candid_WeekSummary_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeekSummary): WeekSummary {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeekSummary]): WeekSummary | null {
    return value.length === 0 ? null : from_candid_WeekSummary_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExcavationView]): ExcavationView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n13(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n17(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pot: bigint;
    treasurePerChip: bigint;
    treasuryKeep: bigint;
    chips: bigint;
    week: bigint;
    drawTicket: bigint;
    drawTickets: bigint;
    closedAt: bigint;
    players: bigint;
    drawPrize: bigint;
    drawWinner: [] | [Principal];
    drawRandom: bigint;
}): {
    pot: bigint;
    treasurePerChip: bigint;
    treasuryKeep: bigint;
    chips: bigint;
    week: bigint;
    drawTicket: bigint;
    drawTickets: bigint;
    closedAt: bigint;
    players: bigint;
    drawPrize: bigint;
    drawWinner?: Principal;
    drawRandom: bigint;
} {
    return {
        pot: value.pot,
        treasurePerChip: value.treasurePerChip,
        treasuryKeep: value.treasuryKeep,
        chips: value.chips,
        week: value.week,
        drawTicket: value.drawTicket,
        drawTickets: value.drawTickets,
        closedAt: value.closedAt,
        players: value.players,
        drawPrize: value.drawPrize,
        drawWinner: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.drawWinner)),
        drawRandom: value.drawRandom
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WeekStatus;
    drawCarry: bigint;
    week: bigint;
    lastClose: [] | [_WeekSummary];
    burned: bigint;
    payouts: Array<_Payout>;
    treasury: bigint;
}): {
    status: WeekStatus;
    drawCarry: bigint;
    week: bigint;
    lastClose?: WeekSummary;
    burned: bigint;
    payouts: Array<Payout>;
    treasury: bigint;
} {
    return {
        status: from_candid_WeekStatus_n32(_uploadFile, _downloadFile, value.status),
        drawCarry: value.drawCarry,
        week: value.week,
        lastClose: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.lastClose)),
        burned: value.burned,
        payouts: from_candid_vec_n34(_uploadFile, _downloadFile, value.payouts),
        treasury: value.treasury
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Principal;
    concept: _PayoutConcept;
    tiers: Array<bigint>;
    amount: bigint;
}): {
    to: Principal;
    concept: PayoutConcept;
    tiers: Array<bigint>;
    amount: bigint;
} {
    return {
        to: value.to,
        concept: from_candid_PayoutConcept_n37(_uploadFile, _downloadFile, value.concept),
        tiers: value.tiers,
        amount: value.amount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WeekStatus;
    mines: bigint;
    feeE8s: bigint;
    minChips: bigint;
    cells: bigint;
    pointsTable: Array<bigint>;
    week: bigint;
    minPlayers: bigint;
    treasuryBps: bigint;
    chipPriceE8s: bigint;
    tierCutsPct: Array<bigint>;
    safePicks: bigint;
    tierMultBps: Array<bigint>;
    faucetCapE8s: bigint;
    excavationsPerChip: bigint;
    drawBps: bigint;
    diamondBps: bigint;
}): {
    status: WeekStatus;
    mines: bigint;
    feeE8s: bigint;
    minChips: bigint;
    cells: bigint;
    pointsTable: Array<bigint>;
    week: bigint;
    minPlayers: bigint;
    treasuryBps: bigint;
    chipPriceE8s: bigint;
    tierCutsPct: Array<bigint>;
    safePicks: bigint;
    tierMultBps: Array<bigint>;
    faucetCapE8s: bigint;
    excavationsPerChip: bigint;
    drawBps: bigint;
    diamondBps: bigint;
} {
    return {
        status: from_candid_WeekStatus_n32(_uploadFile, _downloadFile, value.status),
        mines: value.mines,
        feeE8s: value.feeE8s,
        minChips: value.minChips,
        cells: value.cells,
        pointsTable: value.pointsTable,
        week: value.week,
        minPlayers: value.minPlayers,
        treasuryBps: value.treasuryBps,
        chipPriceE8s: value.chipPriceE8s,
        tierCutsPct: value.tierCutsPct,
        safePicks: value.safePicks,
        tierMultBps: value.tierMultBps,
        faucetCapE8s: value.faucetCapE8s,
        excavationsPerChip: value.excavationsPerChip,
        drawBps: value.drawBps,
        diamondBps: value.diamondBps
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WeekStatus;
    tiers: Array<bigint>;
    balance: bigint;
    diamonds: bigint;
    chips: Array<_ChipView>;
    open: [] | [_ExcavationView];
    paid: bigint;
    week: bigint;
    history: Array<_PlayerWeekResult>;
    totalDiamonds: bigint;
    stats: _WeekStats;
    excavationsLeft: bigint;
    faucetRemaining: bigint;
    estimatedReceive: bigint;
}): {
    status: WeekStatus;
    tiers: Array<bigint>;
    balance: bigint;
    diamonds: bigint;
    chips: Array<ChipView>;
    open?: ExcavationView;
    paid: bigint;
    week: bigint;
    history: Array<PlayerWeekResult>;
    totalDiamonds: bigint;
    stats: WeekStats;
    excavationsLeft: bigint;
    faucetRemaining: bigint;
    estimatedReceive: bigint;
} {
    return {
        status: from_candid_WeekStatus_n32(_uploadFile, _downloadFile, value.status),
        tiers: value.tiers,
        balance: value.balance,
        diamonds: value.diamonds,
        chips: from_candid_vec_n42(_uploadFile, _downloadFile, value.chips),
        open: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.open)),
        paid: value.paid,
        week: value.week,
        history: value.history,
        totalDiamonds: value.totalDiamonds,
        stats: value.stats,
        excavationsLeft: value.excavationsLeft,
        faucetRemaining: value.faucetRemaining,
        estimatedReceive: value.estimatedReceive
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    diamonds: bigint;
    tier: _TierIndex;
    used: bigint;
    avgX100: bigint;
    projectedX100: bigint;
    gapToNextX100: [] | [bigint];
    points: bigint;
}): {
    id: bigint;
    diamonds: bigint;
    tier: TierIndex;
    used: bigint;
    avgX100: bigint;
    projectedX100: bigint;
    gapToNextX100?: bigint;
    points: bigint;
} {
    return {
        id: value.id,
        diamonds: value.diamonds,
        tier: value.tier,
        used: value.used,
        avgX100: value.avgX100,
        projectedX100: value.projectedX100,
        gapToNextX100: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.gapToNextX100)),
        points: value.points
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    collapsed: boolean;
    diamond: boolean;
    ended: boolean;
    pointsSaved: bigint;
    picks: bigint;
    excavation: [] | [_ExcavationView];
}): {
    collapsed: boolean;
    diamond: boolean;
    ended: boolean;
    pointsSaved: bigint;
    picks: bigint;
    excavation?: ExcavationView;
} {
    return {
        collapsed: value.collapsed,
        diamond: value.diamond,
        ended: value.ended,
        pointsSaved: value.pointsSaved,
        picks: value.picks,
        excavation: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.excavation))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pot: bigint;
    status: _WeekStatus;
    treasurePerChip: bigint;
    treasuryKeep: bigint;
    chips: bigint;
    week: bigint;
    totalDiamonds: bigint;
    players: Array<_PlayerRow>;
    drawPrize: bigint;
    cutsX100: Array<[] | [bigint]>;
}): {
    pot: bigint;
    status: WeekStatus;
    treasurePerChip: bigint;
    treasuryKeep: bigint;
    chips: bigint;
    week: bigint;
    totalDiamonds: bigint;
    players: Array<PlayerRow>;
    drawPrize: bigint;
    cutsX100: Array<bigint | null>;
} {
    return {
        pot: value.pot,
        status: from_candid_WeekStatus_n32(_uploadFile, _downloadFile, value.status),
        treasurePerChip: value.treasurePerChip,
        treasuryKeep: value.treasuryKeep,
        chips: value.chips,
        week: value.week,
        totalDiamonds: value.totalDiamonds,
        players: value.players,
        drawPrize: value.drawPrize,
        cutsX100: from_candid_vec_n53(_uploadFile, _downloadFile, value.cutsX100)
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserRole]): [Principal, UserRole] {
    return [
        value[0],
        from_candid_UserRole_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WeekSummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WeekSummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WeekSummary_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AdminView_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PickResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PickResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PickResult_n49(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ExcavationView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ExcavationView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[Principal, _UserRole]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[Principal, UserRole]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payout>): Array<Payout> {
    return value.map((x)=>from_candid_Payout_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChipView>): Array<ChipView> {
    return value.map((x)=>from_candid_ChipView_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [bigint]>): Array<bigint | null> {
    return value.map((x)=>from_candid_opt_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeekSummary>): Array<WeekSummary> {
    return value.map((x)=>from_candid_WeekSummary_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserRole]>): Array<[Principal, UserRole]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
